"""306A Sheet Metal Worker — Batch 3: Q51-75"""
from pathlib import Path

Q51_75 = r"""
,{id:51,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'medium',
text:'When laying out a round elbow using parallel line development, why is the stretchout line equal to the circumference of the duct?',
options:['To account for material stretch during bending','Because the stretchout represents the unrolled surface of the cylinder — its length equals πd','It is equal to the diameter only, not the circumference','SMACNA mandates this for pressure class compliance'],
answer:1,
explanation:'When a cylinder is unrolled flat, its length equals the circumference (πd). The stretchout line represents this unrolled length; heights at each division come from the true-length view.',
keyConcept:'Stretchout = πd (circumference)'},
{id:52,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'hard',
text:'A 45° mitre elbow is cut from round duct. How many gore lines are required for a 3-piece elbow?',
options:['2 gore lines (creating 3 pieces)','3 gore lines (creating 4 pieces)','4 gore lines (creating 5 pieces)','1 gore line (creating 2 pieces)'],
answer:0,
explanation:'A 3-piece elbow has two mitre cuts and one centre section, requiring 2 gore lines. The pieces are: end A, centre gore, end B.',
keyConcept:'3-piece elbow = 2 gore lines'},
{id:53,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'medium',
text:'In pattern development, what does "allowance" refer to?',
options:['The pressure class rating of the duct','Extra material added beyond the true pattern for seams, edges, and connections','The duct velocity in FPM','The sheet metal gauge selected'],
answer:1,
explanation:'Allowances are extra material added to the true pattern for seam laps, wired edges, flanges, or drive cleats — they are not part of the fitting geometry itself.',
keyConcept:'Allowance — extra material for seams/edges'},
{id:54,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'easy',
text:'What drafting instrument is primarily used to scribe arcs and circles when laying out sheet metal patterns?',
options:['Combination square','Trammel points (beam compass) or dividers','Protractor','Framing square'],
answer:1,
explanation:'Trammel points (beam compass) scribe large arcs and circles. Dividers step off equal spaces along curves. Both are essential layout tools for pattern development.',
keyConcept:'Trammel / dividers — pattern layout'},
{id:55,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'hard',
text:'When developing a pattern for a rectangular elbow with a throat radius, which method produces the gore patterns for the curved sections?',
options:['Parallel line development of each rectangular gore','Radial line development from the elbow centreline','Triangulation of the curved face only','Rectangular elbows with radii do not require pattern development — they use standard fittings only'],
answer:0,
explanation:'The curved outer and inner faces of a radius rectangular elbow are developed using parallel line development, with each gore being a trapezoidal flat pattern.',
keyConcept:'Radius rectangular elbow — parallel line gores'},
{id:56,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'medium',
text:'What is the minimum lap dimension for a lap seam in sheet metal ductwork subjected to negative pressure?',
options:['3mm','6mm (1/4")','13mm (1/2")','25mm (1")'],
answer:2,
explanation:'SMACNA requires a minimum 1/2" (13mm) lap for seams on negative-pressure ducts to ensure adequate seal and structural integrity.',
keyConcept:'Lap seam — minimum 13mm (1/2") negative pressure'},
{id:57,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'easy',
text:'What type of snips is designed to cut straight lines and large curves in sheet metal?',
options:['Yellow-handled (left-cut) aviation snips','Red-handled (right-cut) aviation snips','Green-handled (straight-cut) aviation snips','Compound-action snips'],
answer:2,
explanation:'Green-handled aviation snips cut straight and large curves. Red cuts right curves; yellow cuts left curves. Colour coding is standardised for snip selection.',
keyConcept:'Green snips — straight/large curves'},
{id:58,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'hard',
text:'A rectangular duct 600mm×400mm runs 10 metres between transverse joints. At 2" WG positive pressure, what SMACNA requirement applies to the flat panels?',
options:['No intermediate reinforcement required','Intermediate cross-breaking or beading of panels is required','Only corner reinforcement is needed','Standing seams must be added at mid-span'],
answer:1,
explanation:'SMACNA requires intermediate reinforcement (cross-breaking, beading, or standing seams) on large flat panels at elevated pressures to prevent panel flutter and fatigue.',
keyConcept:'Panel reinforcement — SMACNA flat panel requirements'},
{id:59,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'medium',
text:'When using a pop rivet (blind rivet) to join two sheet metal panels, the rivet diameter should be:',
options:['Smaller than the pilot hole by 1mm','A close fit to the pilot hole — rivet diameter matches hole within standard tolerance','Larger than the pilot hole so it expands to fill gaps','Equal to the sheet gauge number'],
answer:1,
explanation:'Pop rivets require a hole that matches the rivet shank diameter closely (within +0.1mm) for proper expansion and clamping. Too large a hole prevents full rivet expansion.',
keyConcept:'Pop rivet — close-fit hole required'},
{id:60,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'medium',
text:'What does "beading" do to a flat sheet metal panel?',
options:['Creates a decorative surface finish','Adds linear indentations that stiffen the panel against buckling and flutter','Removes the sheet metal oxide layer before welding','Creates a sealed hemmed edge'],
answer:1,
explanation:'Beading rolls a small ridge into the panel surface, greatly increasing stiffness by the same principle as corrugation. It prevents oil-canning (panel flutter) in HVAC ductwork.',
keyConcept:'Beading — panel stiffening'},
{id:61,topic:'welding',topicLabel:'Welding & Joining',diff:'medium',
text:'When soldering copper sheet metal, what flux is required and why?',
options:['No flux — copper solders without flux','Acid flux (zinc chloride) to remove oxides and improve solder flow','Alkaline flux for high-temperature brazing only','Anti-spatter compound to prevent solder balls'],
answer:1,
explanation:'Acid (zinc chloride) or rosin flux cleans copper oxide from the surface, allowing solder to wet and flow. Without flux, solder will not bond to oxidised copper.',
keyConcept:'Acid flux — copper soldering'},
{id:62,topic:'welding',topicLabel:'Welding & Joining',diff:'easy',
text:'What is the minimum overlap for a soldered lap joint in sheet metal work?',
options:['Equal to one sheet thickness','3× the sheet thickness','6mm (1/4") minimum','25mm (1") minimum'],
answer:2,
explanation:'A minimum 6mm (1/4") lap is required for soldered joints to develop adequate capillary solder flow and joint strength.',
keyConcept:'Solder lap — 6mm minimum overlap'},
{id:63,topic:'welding',topicLabel:'Welding & Joining',diff:'hard',
text:'A sheet metal worker is spot welding two 20ga mild steel panels. What parameter most directly controls nugget size?',
options:['Electrode material (copper alloy vs carbon)','Weld current (amperage)','Number of spots per metre','Panel orientation (horizontal vs vertical)'],
answer:1,
explanation:'Spot weld nugget size is primarily controlled by current (amperage). Higher current → larger nugget. Weld time and electrode force also affect nugget; current is the dominant variable.',
keyConcept:'Spot weld — current controls nugget size'},
{id:64,topic:'welding',topicLabel:'Welding & Joining',diff:'medium',
text:'After TIG welding stainless steel ductwork, a golden/straw heat tint in the heat-affected zone indicates:',
options:['Proper weld — no action required','Slight oxidation — acceptable for non-critical HVAC applications but passivation is recommended','Severe oxidation — weld must be ground out and redone','Carbide precipitation — the weld is rejected'],
answer:1,
explanation:'Golden/straw tint = slight oxidation, acceptable but not ideal. Dark blue or black tints indicate heavy oxidation requiring mechanical or chemical cleaning (passivation/pickling).',
keyConcept:'Stainless heat tint — straw=acceptable, black=rejected'},
{id:65,topic:'hvac',topicLabel:'HVAC Systems',diff:'medium',
text:'What is the function of a mixing box (mixing damper assembly) in a dual-duct HVAC system?',
options:['It mixes return air with outdoor air','It blends hot deck and cold deck air to achieve the zone setpoint temperature','It mixes supply air with plenum air for pressurisation','It balances airflow between supply and return ducts'],
answer:1,
explanation:'In a dual-duct system, a mixing box blends hot-deck and cold-deck air in varying proportions controlled by zone thermostats to deliver air at the desired temperature.',
keyConcept:'Mixing box — dual-duct hot/cold blending'},
{id:66,topic:'hvac',topicLabel:'HVAC Systems',diff:'easy',
text:'What is the primary purpose of insulating HVAC supply ductwork in an unconditioned attic?',
options:['To prevent condensation on the outside of cold supply ducts and reduce thermal gain/loss','To meet SMACNA pressure class requirements','To reduce duct velocity noise','To allow higher static pressure ratings'],
answer:0,
explanation:'Insulation on supply ducts in unconditioned spaces prevents condensation (cold ducts in humid attics), reduces heat gain from the attic, and improves system efficiency.',
keyConcept:'Duct insulation — condensation prevention + thermal efficiency'},
{id:67,topic:'hvac',topicLabel:'HVAC Systems',diff:'hard',
text:'A sheet metal contractor is installing a kitchen exhaust hood. The duct must be constructed of:',
options:['26ga galvanised steel with standard SMACNA seams','Minimum 16ga carbon steel or 18ga stainless steel with continuous external welds — no seams inside','Aluminium duct rated for 400°F service','Flexible insulated duct, maximum 4m length'],
answer:1,
explanation:'Commercial kitchen exhaust (grease-laden air) requires minimum 16ga black carbon steel or 18ga stainless with all-welded (external) construction — no internal seams or pockets where grease can accumulate.',
keyConcept:'Kitchen exhaust duct — 16ga all-welded construction'},
{id:68,topic:'hvac',topicLabel:'HVAC Systems',diff:'medium',
text:'A duct system shows higher than design static pressure drop across a filter bank. What is the most likely cause?',
options:['Duct leakage downstream of the filter','Filters loaded with dust/dirt (high resistance)','Supply fan speed too low','Excessive outdoor air intake'],
answer:1,
explanation:'A clogged/loaded filter has high resistance, causing elevated pressure drop across the filter section. This also reduces airflow. Filters must be replaced or cleaned.',
keyConcept:'High filter ΔP → filter loading/replacement'},
{id:69,topic:'hvac',topicLabel:'HVAC Systems',diff:'easy',
text:'What is the purpose of a balancing damper installed in a duct branch?',
options:['To prevent backflow in the duct','To throttle airflow to the branch to achieve design CFM during air balancing','To maintain constant static pressure in the main duct','To open automatically when the zone thermostat calls for cooling'],
answer:1,
explanation:'Balancing dampers are manually adjusted during commissioning to set branch airflows to design values. They are locked in position after balancing is complete.',
keyConcept:'Balancing damper — manual commissioning adjustment'},
{id:70,topic:'safety',topicLabel:'Safety & Code',diff:'medium',
text:'When working in a ceiling plenum space above a suspended ceiling, what is a key safety concern specific to sheet metal workers?',
options:['Overhead electrical conduit contact and hidden fall hazards through the ceiling grid','UV radiation from building lights','Chemical hazards from duct sealant curing','Noise levels from HVAC equipment'],
answer:0,
explanation:'Plenum spaces contain energised conduit, communication cables, and the ceiling grid — contact with live wiring or stepping through the grid are key hazards requiring careful footing and awareness.',
keyConcept:'Plenum hazards — electrical contact + fall through ceiling'},
{id:71,topic:'safety',topicLabel:'Safety & Code',diff:'hard',
text:'Under Canadian OH&S regulations, what is required before a worker enters a duct or air handling unit for internal inspection or repair?',
options:['Verbal clearance from the supervisor','A confined space entry permit, atmospheric testing, and a standby person','Lockout of electrical panels only','A safety harness rated for the duct size'],
answer:1,
explanation:'A large AHU or plenum is a confined space. Entry requires: confined space entry permit, atmospheric testing (O2, CO, combustible gas), standby attendant, and rescue plan per CSA Z1006.',
keyConcept:'AHU entry — confined space permit required'},
{id:72,topic:'safety',topicLabel:'Safety & Code',diff:'easy',
text:'Sheet metal edges left from snipping or shearing are extremely sharp. The correct PPE to handle cut sheet metal is:',
options:['Standard leather work gloves','Cut-resistant (level A4 or higher) gloves','Rubber chemical gloves','No gloves — gloves catch on machinery'],
answer:1,
explanation:'Cut-resistant gloves (ANSI/ISEA level A4+ or equivalent) protect against the sharp edges of cut sheet metal. Standard leather gloves provide limited cut resistance.',
keyConcept:'Cut-resistant gloves — sheet metal handling'},
{id:73,topic:'tools',topicLabel:'Tools & Equipment',diff:'medium',
text:'What is a "squaring arm" on a press brake used for?',
options:['Measuring the inside bend angle','Registering (stopping) the sheet at a precise distance from the bend line to ensure consistent flange lengths','Holding the sheet flat during bending','Clamping the die to the press bed'],
answer:1,
explanation:'The squaring arm (back gauge) positions the sheet at a set distance from the die centreline, ensuring each bend produces an identical flange length without re-measuring.',
keyConcept:'Back gauge — consistent flange length positioning'},
{id:74,topic:'tools',topicLabel:'Tools & Equipment',diff:'easy',
text:'A nipper (throatless shear) differs from a guillotine shear in that it:',
options:['Cuts faster and with less force','Can cut curves and irregular shapes because the blade has no frame restricting sheet movement','Only cuts sheet up to 16ga','Uses a rotating circular blade'],
answer:1,
explanation:'A throatless (nipper) shear has no throat frame, so the sheet can be rotated freely during cutting, allowing curved and irregular cuts. A guillotine shear only cuts straight lines.',
keyConcept:'Throatless shear — curves and irregular cuts'},
{id:75,topic:'tools',topicLabel:'Tools & Equipment',diff:'hard',
text:'When using a Pittsburgh lock former (pittsburgh machine) to form a pocket on a panel, what is the correct orientation of the panel relative to the rollers?',
options:['Face side up, the edge to be formed facing the operator','Face side down, edge inserted from the rear','The panel is clamped vertically — orientation does not matter','Edge inserted at 45° to the roller axis'],
answer:0,
explanation:'For a Pittsburgh machine, the panel is fed face-up with the edge to be formed entering the rollers. The machine forms the "pocket" (P-lock groove) along the panel edge.',
keyConcept:'Pittsburgh machine — face up, edge toward rollers'}
"""

# Append to temp file
temp = Path('306a_temp.html')
txt = temp.read_text(encoding='utf-8')
txt += Q51_75
temp.write_text(txt, encoding='utf-8')

import re
ids = re.findall(r'id:\s*(\d+)', txt)
print(f'Batch 3 appended: Q51-75')
print(f'Total questions in temp: {len(ids)}, IDs: {ids[0]}-{ids[-1]}')
print(f'File size: {len(txt):,} chars')
print('Run create_306a_batch4.py next')
