"""306A Sheet Metal Worker — Batch 2: Q26-50"""
from pathlib import Path

Q26_50 = r"""
,{id:26,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'medium',
text:'When developing a pattern for a cylindrical elbow using parallel line development, what determines the number of divisions used around the circumference?',
options:['The sheet gauge','The number of gores in the elbow','The number of divisions on the stretchout line (usually 12 or 16)','The elbow radius'],
answer:2,
explanation:'Parallel line development divides the circumference into equal parts (typically 12 or 16) on the stretchout line; more divisions give a smoother curve.',
keyConcept:'Parallel line — stretchout divisions'},
{id:27,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'hard',
text:'A square-to-round transition connects a 300mm×300mm plenum to a 200mm diameter round duct. Which pattern development method is most appropriate?',
options:['Parallel line development','Radial line development','Triangulation','Seam allowance method'],
answer:2,
explanation:'Triangulation is used for non-developable surfaces like square-to-round transitions. The surface is divided into triangles whose true lengths are found on a true-length diagram.',
keyConcept:'Triangulation — square-to-round'},
{id:28,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'medium',
text:'On a true-length diagram for triangulation, the horizontal base represents:',
options:['The slant height of the transition','The plan (top view) length of each triangle side','The actual sheet metal thickness','The seam allowance'],
answer:1,
explanation:'The horizontal base of a true-length diagram is the horizontal (plan) distance of the line; the vertical leg is the elevation change. The hypotenuse gives the true length.',
keyConcept:'True-length diagram construction'},
{id:29,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'easy',
text:'What is the purpose of a gore line in elbow development?',
options:['It marks where seams are welded','It divides the elbow into equal angular sections for pattern layout','It indicates the allowable bend radius','It marks rivet hole centres'],
answer:1,
explanation:'Gore lines divide a fitting into equal angular segments. Each gore is a mitre section; together they form the elbow curve when assembled.',
keyConcept:'Gore lines — elbow pattern'},
{id:30,topic:'layout',topicLabel:'Layout & Pattern Dev',diff:'hard',
text:'A round-to-round eccentric reducer must be developed. The cone axis does not pass through the apex. Which statement is correct?',
options:['Radial line development applies directly because it is still a cone','Triangulation must be used because true radial lines do not converge at one point','Parallel line development is used since the diameters are round','A template jig replaces pattern development for eccentric fittings'],
answer:1,
explanation:'An eccentric reducer is an oblique cone — radial lines from the apex are not equal length. Triangulation must be used to find true lengths of each element.',
keyConcept:'Oblique cone — triangulation required'},
{id:31,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'easy',
text:'What is the inside bend radius rule of thumb for sheet metal when using a press brake?',
options:['Equal to the sheet thickness','Equal to twice the sheet thickness','Minimum 3× the sheet thickness','Zero — sheet metal bends sharply'],
answer:0,
explanation:'A common rule for mild steel sheet is: minimum inside bend radius ≈ material thickness (1T). Tighter bends risk cracking, especially in harder alloys.',
keyConcept:'Minimum bend radius ≈ 1T'},
{id:32,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'medium',
text:'When calculating the flat blank length for a 90° bend, what correction factor is added to the sum of the two flat legs?',
options:['Bend allowance (BA) — which adds material used in the bend','Setback — which is subtracted from each leg','K-factor multiplied by material thickness — subtracted','Springback allowance — added for elastic recovery'],
answer:0,
explanation:'Flat blank = Leg1 + Leg2 + Bend Allowance. The BA accounts for the arc of material consumed in the bend. (Setback is subtracted from each leg when working from outside dimensions.)',
keyConcept:'Bend allowance in blank layout'},
{id:33,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'medium',
text:'A 24ga galvanized steel duct is being fabricated for a 1" WG positive pressure HVAC system. According to SMACNA, what seam type is required at the minimum?',
options:['Button punch snap lock','Pittsburgh lock seam','Standing seam','Grooved seam (1" or 1.5")'],
answer:1,
explanation:'SMACNA requires Pittsburgh lock seam (or equivalent structural seam) for 1" WG class. Button punch snap lock is limited to lower pressure classes.',
keyConcept:'SMACNA seam class vs pressure'},
{id:34,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'hard',
text:'Which type of transverse joint is rated by SMACNA for use in ducts up to 4" WG?',
options:['Slip-and-drive (S & Drive)','Companion angle flange','SMACNA TDC/TDF flange','Pocket lock'],
answer:2,
explanation:'TDC (Transverse Duct Connector) and TDF (Transverse Duct Flange) systems are rated to 4" WG and higher when properly installed per SMACNA tables.',
keyConcept:'TDC/TDF — high pressure transverse joint'},
{id:35,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'medium',
text:'What is the primary purpose of a "break" or "hem" along the raw edge of a sheet metal panel?',
options:['To increase airflow velocity','To stiffen the edge and eliminate the sharp cut hazard','To provide a surface for sealant application','To allow thermal expansion'],
answer:1,
explanation:'A hem folds the raw cut edge back on itself, removing the sharp edge hazard and adding rigidity to the panel edge.',
keyConcept:'Hem — edge safety and stiffness'},
{id:36,topic:'fabrication',topicLabel:'Sheet Metal Fabrication',diff:'easy',
text:'What hand tool is used to close a Pittsburgh lock seam in the field?',
options:['Aviation snips','Seaming pliers (hand seamer)','Pop rivet gun','Offset hammer'],
answer:1,
explanation:'A hand seamer (seaming pliers) grips and folds the Pittsburgh lock pocket closed over the inserted panel edge, completing the longitudinal seam.',
keyConcept:'Hand seamer — Pittsburgh lock closing'},
{id:37,topic:'welding',topicLabel:'Welding & Joining',diff:'medium',
text:'When MIG welding galvanized sheet metal, what is the primary safety hazard that requires special ventilation?',
options:['UV radiation only','Zinc oxide fumes — toxic even at low concentrations','Ozone from the shielding gas','Spatter igniting the sheet'],
answer:1,
explanation:'Burning the zinc coating releases zinc oxide fumes that cause metal fume fever. Local exhaust ventilation and a respirator rated for metal fumes are required.',
keyConcept:'Zinc oxide fumes — galvanized welding hazard'},
{id:38,topic:'welding',topicLabel:'Welding & Joining',diff:'medium',
text:'What shielding gas mixture is typically preferred for MIG welding mild steel sheet metal (thin gauge)?',
options:['100% CO2','75% Ar / 25% CO2','100% Argon','50% He / 50% Ar'],
answer:1,
explanation:'75/25 Ar/CO2 (C25) gives stable arc, lower spatter, and good penetration for thin mild steel. 100% CO2 causes more spatter; pure Ar is used for aluminium.',
keyConcept:'C25 shielding gas — mild steel MIG'},
{id:39,topic:'welding',topicLabel:'Welding & Joining',diff:'hard',
text:'Stainless steel HVAC ductwork is being fabricated. What welding process minimises heat input and distortion best?',
options:['SMAW with E308 electrode','GMAW with short-circuit transfer','GTAW (TIG) with ER308L filler','FCAW with E308LT wire'],
answer:2,
explanation:'GTAW (TIG) provides the most precise heat control and lowest distortion for thin stainless. ER308L filler reduces carbide precipitation risk.',
keyConcept:'TIG — stainless steel, low distortion'},
{id:40,topic:'welding',topicLabel:'Welding & Joining',diff:'easy',
text:'What is the purpose of tack welds during sheet metal assembly?',
options:['To provide the final weld strength','To temporarily hold parts in position before full welding','To replace clamps on thin material','To test electrode compatibility'],
answer:1,
explanation:'Tack welds temporarily hold parts in alignment and at correct dimensions before full seam welding, preventing movement and distortion during welding.',
keyConcept:'Tack welds — positioning function'},
{id:41,topic:'hvac',topicLabel:'HVAC Systems',diff:'easy',
text:'What does the acronym AHU stand for in HVAC systems?',
options:['Air Handling Unit','Automatic Heat Updraft','Airflow Humidity Unit','Auxiliary Heating Unit'],
answer:0,
explanation:'AHU (Air Handling Unit) conditions and circulates air: it contains a fan, heating/cooling coils, filters, and dampers. Sheet metal ductwork connects to AHU supply and return.',
keyConcept:'AHU — Air Handling Unit'},
{id:42,topic:'hvac',topicLabel:'HVAC Systems',diff:'medium',
text:'A VAV (Variable Air Volume) system modulates airflow to individual zones. What controls the airflow at each zone terminal?',
options:['A fixed orifice plate','A VAV box with a motorised damper controlled by a thermostat','Manual balancing dampers adjusted at commissioning','The AHU fan speed only'],
answer:1,
explanation:'VAV boxes contain a modulating damper controlled by the zone thermostat. They vary airflow from maximum to minimum (or zero) to maintain setpoint temperature.',
keyConcept:'VAV box — zone damper control'},
{id:43,topic:'hvac',topicLabel:'HVAC Systems',diff:'medium',
text:'According to SMACNA, what is the maximum recommended velocity in a low-velocity supply duct main to control noise?',
options:['500 FPM','900 FPM','1,500 FPM (≈7.5 m/s)','2,500 FPM'],
answer:2,
explanation:'SMACNA low-velocity design guidelines recommend ≤1,500 FPM (about 7.5 m/s) in main supply ducts to limit noise generation. Branches are typically lower.',
keyConcept:'Max duct velocity — low-velocity design'},
{id:44,topic:'hvac',topicLabel:'HVAC Systems',diff:'hard',
text:'What is the purpose of a static pressure regain fitting at a duct branch takeoff?',
options:['To increase duct velocity at the branch','To recover static pressure as velocity decreases, improving system balance','To seal the branch from leakage','To add return air to the branch'],
answer:1,
explanation:'As velocity drops at a branch, a regain fitting converts velocity pressure back to static pressure. This static regain partially offsets pressure loss, improving system balance.',
keyConcept:'Static pressure regain — velocity to static conversion'},
{id:45,topic:'hvac',topicLabel:'HVAC Systems',diff:'medium',
text:'A sheet metal worker is installing a flexible connection (flex connector) between the AHU and rigid ductwork. What is the primary purpose?',
options:['To allow disassembly for duct cleaning','To isolate vibration from the AHU fan from the duct system','To increase duct cross-section area','To act as a volume control damper'],
answer:1,
explanation:'Flexible connections (canvas or neoprene) absorb AHU fan vibration, preventing noise and fatigue cracks in the rigid ductwork and building structure.',
keyConcept:'Flex connector — vibration isolation'},
{id:46,topic:'safety',topicLabel:'Safety & Code',diff:'easy',
text:'What WHMIS 2015 pictogram indicates a gas under pressure (compressed gas cylinder)?',
options:['Flame over circle (oxidizer)','Gas cylinder pictogram (black cylinder on white)','Exclamation mark','Skull and crossbones'],
answer:1,
explanation:'The gas cylinder pictogram (silhouette of a cylinder) identifies gases under pressure — compressed, liquefied, or dissolved gases — per WHMIS 2015 / GHS.',
keyConcept:'WHMIS gas cylinder pictogram'},
{id:47,topic:'safety',topicLabel:'Safety & Code',diff:'medium',
text:'A sheet metal worker is cutting 16ga steel with a plasma cutter. Eye protection must be at minimum:',
options:['Shade #3 safety glasses','Shade #5 face shield','Shade #8 welding lens or higher','No eye protection required — plasma is not welding'],
answer:2,
explanation:'Plasma cutting produces intense UV/IR radiation. CSA/ANSI recommend shade #8 minimum for plasma cutting. Shades 5-6 are used for light gas cutting; shade 8+ for plasma.',
keyConcept:'Plasma cutting — shade #8 minimum'},
{id:48,topic:'safety',topicLabel:'Safety & Code',diff:'medium',
text:'Before starting any work on an energised electrical panel in the mechanical room where ductwork is being installed, the sheet metal worker must:',
options:['Notify the foreman verbally','Apply LOTO (Lockout/Tagout) procedures on all energy sources','Simply turn off the panel breaker and proceed','Wear rubber gloves only'],
answer:1,
explanation:'LOTO (Lockout/Tagout) is mandatory before working near or on energised equipment. The sheet metal worker must de-energise, lock out, and verify zero energy state.',
keyConcept:'LOTO — mandatory near energised panels'},
{id:49,topic:'tools',topicLabel:'Tools & Equipment',diff:'medium',
text:'What is a "jenny" (jenny wheel or rotary machine) used for in a sheet metal shop?',
options:['Cutting circles from flat sheet','Forming turned edges, flanges, and wired edges on curved sheet metal','Punching holes for rivets','Rolling flat sheet into cylinders'],
answer:1,
explanation:'A jenny (turning machine / jenny wheel) forms a right-angle flange or turned edge along a curved or straight edge of sheet metal — used for elbow flanges and wired edges.',
keyConcept:'Jenny — turned edge / flange forming'},
{id:50,topic:'tools',topicLabel:'Tools & Equipment',diff:'hard',
text:'A slip roll machine has three rollers. What is the function of the rear (adjustable) roller relative to the two front rollers?',
options:['It drives the sheet through the machine','It controls the diameter of the cylinder being rolled by adjusting its height relative to the front rollers','It cuts the sheet to width','It applies a locking force to prevent springback'],
answer:1,
explanation:'The rear roller is adjustable up/down. Moving it closer to the front rollers increases curvature (smaller diameter); backing it off reduces curvature. The two front rollers feed/drive the sheet.',
keyConcept:'Slip roll — rear roller controls cylinder diameter'}
"""

# Append to temp file
temp = Path('306a_temp.html')
txt = temp.read_text(encoding='utf-8')
txt += Q26_50
temp.write_text(txt, encoding='utf-8')

import re
ids = re.findall(r'id:\s*(\d+)', txt)
print(f'Batch 2 appended: Q26-50')
print(f'Total questions in temp: {len(ids)}, IDs: {ids[0]}-{ids[-1]}')
print(f'File size: {len(txt):,} chars')
print('Run create_306a_batch3.py next')
