"""
403a.html Quiz - Part 2
Appends questions 51-100 + JS engine + closing HTML to 403a_new.html
Then moves 403a_new.html -> 403a.html
"""
from pathlib import Path

BASE = Path(__file__).parent.parent

QUESTIONS_51_100 = r"""
,
// ── PIPING continued (51-56) ──
{id:51,topic:'piping',topicLabel:'Piping Systems',diff:'medium',text:'Why is copper tubing NOT approved for LP (propane) gas service?',options:['A) Copper is too soft for gas pressure','B) Propane contains compounds (including some LP odourants) that can corrode copper and form blockages in valves and regulators','C) Copper expands too much with temperature changes','D) Copper is approved for LP gas in all Canadian jurisdictions'],answer:1,explanation:'LP gas (propane) may contain compounds including certain mercaptan odourants that react with copper to form copper mercaptide deposits. These deposits can block orifices, valve seats, and regulator passages. CSA B149.1 prohibits copper for LP gas service. Copper is acceptable for natural gas.',keyConcept:'Copper: approved for natural gas, NOT for LP/propane. Propane odourants react with copper → deposits in orifices and valves. Use black steel, CSST, or PE for propane systems.'},
{id:52,topic:'piping',topicLabel:'Piping Systems',diff:'medium',text:'What special consideration applies when installing gas piping in concealed spaces (inside walls, above ceilings)?',options:['A) Concealed piping must use larger diameter pipe','B) Concealed gas piping must be continuous without fittings (no unions, couplings) in the concealed section, and CSST must be properly protected from physical damage','C) No restrictions apply to piping inside building cavities','D) Concealed piping must be wrapped in fireproof insulation'],answer:1,explanation:'CSA B149.1 prohibits mechanical joints (unions, couplings) in concealed spaces — pipe must be continuous. Any fittings in concealed spaces must be welded (for steel) or press-fit rated for gas. CSST in stud walls must be protected from nails/screws with steel shield plates. This prevents undetectable gas leaks inside walls.',keyConcept:'Concealed gas piping: no unions/couplings in wall cavities. Pipe must be continuous. CSST requires steel protection plates at stud locations. Any leak in concealed space = major hazard.'},
{id:53,topic:'piping',topicLabel:'Piping Systems',diff:'hard',text:'A commercial kitchen requires 500,000 BTU/h of natural gas. The run from the meter is 20 m of 2" black steel pipe. The allowable pressure drop is 125 Pa (0.5 in WC). Using a pipe capacity table, what is the required pipe diameter?',options:['A) 1.5" pipe is sufficient for 500,000 BTU/h at 20m','B) 2" pipe — at 20m, 2" pipe handles 400,000-600,000 BTU/h at 125 Pa pressure drop (verify with CSA B149.1 tables)','C) 3" pipe — always required for commercial loads above 200,000 BTU/h','D) 1" pipe — pressure drop tables are not needed for short runs'],answer:1,explanation:'Gas pipe sizing requires using CSA B149.1 Appendix tables. For natural gas at standard conditions with 125 Pa (0.5 in WC) allowable pressure drop: 2" pipe at 20m typically carries 450,000-600,000 BTU/h. Always use the official tables for the exact supply pressure, pipe length, and allowable drop in your jurisdiction.',keyConcept:'Gas pipe sizing: use CSA B149.1 Appendix tables. Inputs: BTU/h demand, pipe length, supply pressure, allowable pressure drop. Add equivalent length for fittings (each elbow adds ~1m equivalent).'},
{id:54,topic:'piping',topicLabel:'Piping Systems',diff:'hard',text:'What happens to gas pressure in a pipe as flow rate increases and why does this matter for pipe sizing?',options:['A) Pressure increases with flow — pipe must be sized to withstand higher pressure','B) Pressure drops with flow due to friction losses — pipes must be sized so pressure drop stays within allowable limits to maintain adequate appliance inlet pressure','C) Pressure is constant regardless of flow rate in a properly sized system','D) Pressure increases then decreases — only the midpoint matters for sizing'],answer:1,explanation:'As gas flows through a pipe, friction causes pressure to drop. The greater the flow rate, the greater the pressure drop per unit length. Pipe sizing ensures that pressure drop from the supply (meter) to the most distant appliance stays within allowable limits (125 Pa for residential NG), maintaining adequate appliance inlet pressure for proper combustion.',keyConcept:'Pressure drop increases with flow rate and pipe length, decreases with pipe diameter. Sizing objective: keep total pressure drop from meter to appliance within allowable limit.'},
{id:55,topic:'piping',topicLabel:'Piping Systems',diff:'medium',text:'When gas piping passes through a concrete foundation wall, what protection is required?',options:['A) The pipe can be installed directly through concrete with no protection','B) The pipe must pass through a protective sleeve or casing, sealed at the exterior end against moisture, with the annular space vented to the exterior','C) The pipe must be coated with epoxy paint inside the concrete','D) The pipe must be wrapped in fiberglass insulation before passing through concrete'],answer:1,explanation:'Gas pipe through foundation walls requires a sleeve/casing to protect the pipe from abrasion and concrete chemicals, and to allow for ground movement. The annular space is sealed at the exterior end (weather side) to prevent moisture entry. The interior end must not be sealed to allow any gas accumulation to vent.',keyConcept:'Gas pipe through foundation: sleeve/casing required. Seal exterior end (weather protection). Do NOT seal interior end — allows venting of any trapped gas. Pipe must not be in contact with concrete.'},
{id:56,topic:'piping',topicLabel:'Piping Systems',diff:'medium',text:'What is the key difference between CSST and rigid black steel pipe in terms of installation requirements?',options:['A) CSST is cheaper — no other differences','B) CSST is flexible and can be routed around obstacles, but requires bonding/grounding, protection from physical damage at framing penetrations, and specific fittings — rigid steel uses threaded or welded connections','C) CSST must be installed by a licensed electrician due to bonding requirements','D) CSST can only be used outdoors in Canada'],answer:1,explanation:'CSST advantages: flexibility, faster installation, fewer fittings, can be fished through walls. CSST requirements: electrical bonding (lightning protection), steel protection plates at framing penetrations, specific end fittings (not standard NPT thread sealant connections), and must follow manufacturer installation guide.',keyConcept:'CSST vs black steel: CSST = flexible + fast installation but requires bonding + protection plates. Steel = rigid + standard threaded fittings. Both require CSA B149.1 compliance.'},
// ── VENTING (57-72) ──
{id:57,topic:'venting',topicLabel:'Venting Systems',diff:'easy',text:'What defines a "direct vent" (sealed combustion) gas appliance?',options:['A) An appliance that vents directly through the roof without a chimney','B) An appliance that draws all combustion air from outside and vents all flue gases to outside through a sealed two-pipe system, completely isolated from interior air','C) An appliance with a direct connection to the gas main','D) An appliance that vents directly into the return air plenum'],answer:1,explanation:'Direct vent (sealed combustion) appliances use a concentric or twin-pipe system — one pipe supplies fresh outdoor combustion air, the other exhausts flue gases. The combustion process is isolated from the building interior. No interior combustion air is required, making them ideal for tight, well-insulated buildings.',keyConcept:'Direct vent: sealed combustion — two-pipe system (combustion air in, flue out). No interior air consumption. Works in airtight buildings. Most common in high-efficiency condensing appliances.'},
{id:58,topic:'venting',topicLabel:'Venting Systems',diff:'easy',text:'What is the minimum upward slope (pitch) required for a horizontal vent connector on a natural draft gas appliance?',options:['A) Level (no slope needed)','B) Minimum 1/4 inch per foot (2%) upward slope toward the vent terminal or chimney','C) Minimum 1 inch per foot (8%) downward slope toward the appliance','D) No slope required — draft creates its own flow'],answer:1,explanation:'Vent connectors (single-wall metal flue pipe) on natural draft appliances must slope upward at minimum 1/4 inch per foot (2%) toward the vent terminal. This helps buoyancy drive flue gases upward and prevents condensate from draining back into the appliance. Negative slope causes spillage and appliance damage.',keyConcept:'Vent connector slope: minimum 1/4" per foot (2%) upward toward chimney/terminal. Negative slope = condensate runs into appliance + poor draft. Check slope before commissioning.'},
{id:59,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What is Type B double-wall metal vent (B-vent) and what appliances use it?',options:['A) Single-wall metal flue pipe for high-temperature applications','B) Double-wall metal vent (inner aluminum, outer galvanized steel) with insulating air space, used for natural draft Category I gas appliances','C) Stainless steel vent liner used inside masonry chimneys','D) PVC vent pipe used for condensing appliances'],answer:1,explanation:'Type B vent consists of an inner aluminum alloy liner and an outer galvanized steel jacket with an insulating air gap between them. The insulation keeps the inner liner warm, maintaining flue gas temperature above the dew point and promoting draft. Used for natural draft Category I gas appliances (atmospheric furnaces, water heaters).',keyConcept:'B-vent: inner aluminum + outer galvanized + air gap insulation. Keeps flue gas warm → maintains draft → prevents condensation. For natural draft Category I appliances only.'},
{id:60,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What are the four categories of gas appliance venting classification?',options:['A) Types A, B, C, D based on flue pipe material','B) Categories I-IV based on vent static pressure (positive or non-positive) and flue gas temperature relative to dew point','C) Classes 1-4 based on appliance BTU rating','D) Grades I-IV based on appliance efficiency'],answer:1,explanation:'Categories per CSA B149.1: Cat I = non-positive pressure, above dew point (80% furnace). Cat II = non-positive pressure, below dew point (condensing, low temp). Cat III = positive pressure, above dew point (some direct vent). Cat IV = positive pressure, below dew point (condensing, high efficiency). Venting material requirements differ for each.',keyConcept:'Venting Categories: Cat I (natural draft, no condensate) → B-vent. Cat II (natural draft, condensate). Cat III (pressurized, no condensate). Cat IV (pressurized, condensate) → PVC/CPVC/SS liner.'},
{id:61,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What is the purpose of a draft hood on an atmospheric (natural draft) gas furnace?',options:['A) To increase chimney draft by restricting flue gas flow','B) To dilute flue gases with room air and provide a break point — preventing chimney downdraft from extinguishing the burner, and allowing dilution air to enter if combustion is disrupted','C) To filter combustion gases before they enter the vent','D) To provide combustion air directly to the burner'],answer:1,explanation:'The draft hood (draft diverter) serves three functions: 1) Breaks the connection between chimney draft and appliance (variations in chimney draft don\'t affect burner), 2) Allows room air dilution of flue gases, 3) Provides spillage path if chimney is blocked — flue gases spill at the draft hood rather than being forced through the heat exchanger in reverse.',keyConcept:'Draft hood: decouples appliance from chimney draft variations. Provides spillage path if chimney blocked. Allows air dilution. Inspect for spillage (soot at hood = problem).'},
{id:62,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What is the minimum clearance from a gas appliance vent termination to a window or door opening?',options:['A) 300 mm (12 in)','B) 600 mm (24 in) for Category I natural draft; 300-600 mm for direct vent terminals depending on BTU rating — verify with CSA B149.1','C) 1.0 m (40 in) for all appliances','D) 150 mm (6 in) if wind direction is not toward the opening'],answer:1,explanation:'CSA B149.1 specifies minimum clearances from vent terminals to openings. For natural draft vent terminals: minimum 600 mm (24 in) from any window, door, or opening that can be opened. Direct vent terminals have specific clearances based on BTU rating. Always verify with current code as requirements vary by appliance type and capacity.',keyConcept:'Vent termination clearances (CSA B149.1): minimum 600mm from operable windows/doors for natural draft. Direct vent: 300-600mm depending on BTU. Check current edition for exact requirements.'},
{id:63,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'When two gas appliances share a common vent, what must be considered?',options:['A) The larger appliance vents normally; the smaller one must use a separate vent','B) The common vent must be sized to handle the combined flue gas volume — using CSA B149.1 common vent sizing tables considering both appliance types, BTU ratings, and heights','C) Common venting always reduces vent size requirements','D) Only matching appliance types (e.g., two furnaces) may share a common vent'],answer:1,explanation:'Common venting of two Category I appliances is permitted under specific conditions. The common vent segment must be sized using B149.1 tables for the combined total BTU input, considering: height of the vertical common vent, individual connector lengths, and both appliance types. Improper sizing causes spillage at one appliance.',keyConcept:'Common vent sizing: use B149.1 tables for combined BTU, vent height, connector lengths. Category I only. Fan-assisted appliances with atmospherics require special analysis.'},
{id:64,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What vent material is required for a Category IV condensing gas appliance (e.g., 95% AFUE furnace)?',options:['A) Type B double-wall metal vent (B-vent)','B) Schedule 40 PVC, CPVC, or stainless steel liner — must be rated for moist acidic condensate and positive pressure','C) Single-wall galvanized steel vent connector','D) Masonry chimney with clay tile liner'],answer:1,explanation:'Category IV appliances produce acidic condensate (pH 3-4) and operate at positive vent pressure. Ordinary metal vents corrode rapidly. Approved materials: Schedule 40 PVC (if flue gas temperature stays below PVC limits), CPVC, or stainless steel vent liners. The vent pipe must handle both positive pressure and acidic condensate.',keyConcept:'Category IV vent material: PVC/CPVC (if flue gas temp <60°C at pipe) or stainless steel liner. Condensate must drain to proper drain — install condensate trap in vent.'},
{id:65,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What is the maximum horizontal run permitted for a power-vent (Category III) appliance vent?',options:['A) 600 mm (2 ft) — power vents must be nearly vertical','B) As specified by the appliance manufacturer — typically up to 15-25 m depending on the number of elbows and pipe size','C) No limit — power venting can run any distance horizontally','D) Maximum 3 m regardless of appliance size'],answer:1,explanation:'Power-vent (Category III) appliances use a blower to push flue gases through the vent. Maximum horizontal run depends on the appliance manufacturer\'s specifications and the vent system\'s static pressure capacity. Each elbow reduces equivalent straight-pipe capacity. Exceeding maximum run reduces flue gas velocity and can cause condensate accumulation.',keyConcept:'Power vent horizontal run: follow manufacturer specs (typically 15-25m total equivalent length). Each 90° elbow = ~1.5m equivalent. Exceed limit = insufficient draft, condensate problems.'},
{id:66,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'When can PVC pipe be used for venting a gas appliance in Canada?',options:['A) PVC can be used for any gas appliance venting as a cost-saving measure','B) PVC (Schedule 40) is permitted for Category IV condensing appliances where the flue gas temperature remains below the PVC temperature rating throughout the vent, per appliance listing and manufacturer\'s instructions','C) PVC venting is prohibited in Canada under all circumstances','D) PVC is permitted for venting only in mild climates'],answer:1,explanation:'PVC Schedule 40 vent pipe is permitted for Category IV condensing appliances when the flue gas temperature stays within PVC\'s temperature limits (typically <65°C/150°F at the pipe). The appliance must be listed for PVC venting and the manufacturer\'s instructions must specifically permit it. Not all condensing appliances are listed for PVC.',keyConcept:'PVC venting: permitted for Category IV only, when flue gas temp stays below PVC limit AND appliance is listed for PVC. Check appliance listing — not all condensing appliances allow PVC.'},
{id:67,topic:'venting',topicLabel:'Venting Systems',diff:'hard',text:'A 403A gas fitter is installing a 120,000 BTU/h natural draft water heater in a utility room. What combustion air volume is required for the room per CSA B149.1?',options:['A) No combustion air required — water heaters use indoor air without restriction','B) For appliances in a confined space: 0.08 m²/kW free area of openings to an unconfined space — calculate: 120,000 BTU/h = 35.2 kW × 0.08 m²/kW = 2.8 m² of free opening area','C) Minimum one 300 mm × 300 mm louvre in the door','D) The room must have one window that opens to the exterior'],answer:1,explanation:'CSA B149.1 combustion air for confined space: open-combustion appliances require 0.08 m²/kW of free area of openings. Converting: 120,000 BTU/h ÷ 3,412 = 35.2 kW × 0.08 m²/kW = 2.8 m² of free area. This is typically two openings (one at high, one at low). This ensures adequate combustion air and prevents negative pressure draft problems.',keyConcept:'Combustion air calc: 0.08 m²/kW free opening area for confined spaces with open-combustion appliances. Two openings: one within 300mm of ceiling, one within 300mm of floor.'},
{id:68,topic:'venting',topicLabel:'Venting Systems',diff:'hard',text:'A 403A gas fitter inspects an existing chimney before connecting a new gas appliance. The chimney is 150mm (6") clay tile lined and serves an oil furnace. The new gas appliance is 80,000 BTU/h natural draft. What concern must be addressed?',options:['A) No concern — any chimney approved for oil is approved for gas','B) Gas appliances produce lower-temperature, wetter flue gases than oil — the larger chimney may be oversized, causing flue gases to cool and condense, corroding the clay tile liner. A liner may be required','C) The chimney must be re-rated for gas before any work begins','D) No concern — chimney relining is never required when switching from oil to gas'],answer:1,explanation:'Gas appliances produce cooler, more moisture-laden flue gases than oil. An oversized oil chimney with a gas appliance can cause: 1) Flue gases cooling below dew point = condensate production, 2) Acidic condensate attacking clay tile, 3) Poor draft due to oversized flue area. Solution: install a listed stainless steel liner sized for the gas appliance BTU rating.',keyConcept:'Oil to gas chimney conversion: gas flue gases are cooler and wetter. Oversized oil chimney → condensate → clay tile damage. Install stainless steel liner sized for gas appliance.'},
{id:69,topic:'venting',topicLabel:'Venting Systems',diff:'hard',text:'What is a spillage test for a natural draft gas appliance and when must it be performed?',options:['A) A test to detect gas leaking from vent connections','B) A test to verify flue gases are actually going up the vent and not spilling into the room — performed after each installation and commissioning of a natural draft appliance','C) A pressure test for the vent pipe joints','D) A test for CO in the flue gas after combustion analysis'],answer:1,explanation:'A spillage test checks that combustion gases are properly venting. Method: hold a smoke pencil or incense stick at the draft hood opening — smoke should be drawn up into the vent (not spill into room). Test with all exhaust fans running (worst case). Spillage indicates blocked vent, insufficient combustion air, negative pressure in building, or improper vent sizing.',keyConcept:'Spillage test: smoke/incense at draft hood opening → smoke drawn in = proper draft. Smoke pushed out = spillage = CO risk. Test with all exhaust fans running (worst case).'},
{id:70,topic:'venting',topicLabel:'Venting Systems',diff:'hard',text:'A Category II gas appliance operates in non-positive pressure with flue gas below the dew point. What special vent considerations apply?',options:['A) Category II uses standard B-vent — no special considerations','B) Category II appliances produce condensate but operate at non-positive pressure — vent must handle acidic condensate drainage, and must be of corrosion-resistant material (AL29-4C stainless or listed plastic)','C) Category II requires positive pressure metal vent only','D) Category II is rarely encountered and no standard exists'],answer:1,explanation:'Category II appliances (non-positive pressure, condensing conditions) are uncommon but do exist. The vent must resist acidic condensate even though it operates at negative (or zero) pressure. Special venting materials are required. Condensate drainage from the vent back to the appliance or to a floor drain is necessary.',keyConcept:'Category II: non-positive pressure + condensate. Uncommon appliance type. Requires corrosion-resistant vent material. Must drain condensate. Examples: some atmospheric condensing water heaters.'},
{id:71,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'Where are carbon monoxide detectors required in relation to gas appliances?',options:['A) CO detectors are optional — only smoke detectors are code-required','B) CO detectors are required in all residential buildings with fuel-burning appliances and in sleeping areas — specific placement per provincial fire/building codes','C) CO detectors must be installed inside the furnace room only','D) CO detectors are only required in buildings with atmospheric water heaters'],answer:1,explanation:'Most provincial building and fire codes require CO detectors in residential buildings with fuel-burning appliances. Requirements vary by province but generally: at least one CO detector per floor, and one within proximity of each sleeping area. CO detectors are also recommended near each appliance but should not be placed directly above them.',keyConcept:'CO detector placement: per provincial fire code. Typically: one per floor + outside sleeping areas. Not inside furnace room (too hot, too close). At breathing height (CO is near-neutral buoyancy).'},
{id:72,topic:'venting',topicLabel:'Venting Systems',diff:'medium',text:'What must a 403A gas fitter verify about vent termination height above a flat roof?',options:['A) Vent can terminate at roof level — no height requirement','B) Vent terminal must extend a minimum height above the roof surface as specified in CSA B149.1 (typically 600 mm above a flat roof within 600 mm of the terminal) to prevent flue gas re-entrainment during wind','C) Vent must extend to the highest point of the building','D) 150 mm above the roof is sufficient for all appliances'],answer:1,explanation:'CSA B149.1 requires vent terminals to extend above the roof to prevent flue gas re-entry during wind conditions. For flat roofs: terminal must extend above the roof line with clearances from any adjacent wall that would cause downwash. Minimum heights are specified based on roof type and distance from roof edge or adjacent walls.',keyConcept:'Vent terminal height: must extend above roof per CSA B149.1 clearances. Prevents wind-induced flue gas re-entrainment. Verify current code for exact height for roof type.'},
// ── COMBUSTION (73-86) ──
{id:73,topic:'combustion',topicLabel:'Combustion Theory',diff:'easy',text:'What are the primary components of natural gas as distributed in Canada?',options:['A) Equal parts methane, propane, and butane','B) Primarily methane (CH4) — typically 90-95%, with small amounts of ethane, propane, butane, and inert gases','C) Primarily propane with methane added for odour','D) Equal parts hydrogen and methane'],answer:1,explanation:'Pipeline natural gas is primarily methane (CH4), typically 90-95%, with minor amounts of ethane (C2H6), propane (C3H8), and butane (C4H10), plus inert gases (N2, CO2). The exact composition varies by source and region. This composition determines energy content (~1,000 BTU/ft3) and combustion characteristics.',keyConcept:'Natural gas composition: ~90-95% methane (CH4). Small amounts ethane, propane, butane. Inerts: N2, CO2. Energy content: ~37 MJ/m3 (1,000 BTU/ft3). Heating value varies slightly by source.'},
{id:74,topic:'combustion',topicLabel:'Combustion Theory',diff:'easy',text:'What does the colour of a gas burner flame indicate about combustion quality?',options:['A) Blue flame = too much air; yellow flame = correct mixture','B) Blue flame = correct air-fuel mixture (complete combustion); yellow/orange flame = insufficient air or incorrect mixture (incomplete combustion)','C) Yellow is normal for natural gas; blue is normal for propane only','D) Flame colour is decorative and has no combustion significance'],answer:1,explanation:'A steady blue flame indicates complete combustion with proper air-fuel mixture. Blue comes from excited CH radicals. Yellow/orange flames indicate incomplete combustion — carbon particles glow yellow before they can fully oxidize, producing soot and CO. A few yellow tips at the top of flame is acceptable; fully yellow flame is not.',keyConcept:'Blue flame = complete combustion, correct air-fuel ratio. Yellow/orange = incomplete combustion, insufficient air, wrong gas pressure, or dirty burner. Yellow = CO production risk.'},
{id:75,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What is stoichiometric combustion?',options:['A) Combustion with excess air — the safest type for gas appliances','B) Combustion with exactly the theoretical amount of air required to completely combust all fuel — no excess air and no incomplete combustion','C) Combustion with insufficient air, producing maximum heat output','D) Combustion at the highest possible flame temperature'],answer:1,explanation:'Stoichiometric combustion uses exactly the theoretical air-fuel ratio: all fuel molecules react with exactly enough oxygen molecules, producing only CO2 and H2O with no excess O2 remaining. In practice, gas appliances operate with some excess air (5-15%) to ensure complete combustion, as perfect stoichiometry is difficult to achieve in real conditions.',keyConcept:'Stoichiometric: exact theoretical air-fuel ratio → all fuel combusted, zero excess O2. Real appliances: 5-15% excess air. Too little air = CO; too much air = high flue losses.'},
{id:76,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What is the difference between primary air and secondary air in gas burner combustion?',options:['A) Primary air comes from outside; secondary air is recycled flue gas','B) Primary air mixes with gas before combustion at the burner (in the venturi/mixing tube); secondary air surrounds the flame and provides additional O2 for complete combustion','C) They are the same air entering from different locations','D) Primary air is for ignition only; secondary air maintains the flame'],answer:1,explanation:'In an atmospheric (Bunsen-type) burner: primary air is drawn into the mixing tube by the venturi effect of gas flow and mixes with gas before the burner port. Secondary air surrounds the flame from the atmosphere, providing additional oxygen for complete combustion. Proper primary/secondary air balance is critical for flame appearance and combustion quality.',keyConcept:'Primary air: mixes with gas before burner (in venturi) → blue cone at flame base. Secondary air: surrounds flame from atmosphere → completes combustion at outer envelope.'},
{id:77,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'During a combustion analysis, the CO2 reading in the flue gas of a natural gas furnace is 8.5%. What does this indicate?',options:['A) 8.5% CO2 indicates perfect combustion efficiency','B) CO2 of 8.5% is below the stoichiometric maximum (~12% for NG), indicating excess air — higher excess air dilutes CO2 concentration and increases flue gas volume and heat loss','C) 8.5% CO2 is too high — CO2 should never exceed 5% in flue gas','D) CO2 has no relevance to combustion quality analysis'],answer:1,explanation:'Maximum theoretical CO2 for natural gas (stoichiometric) is approximately 11.7-12.5%. In practice, residential furnaces read 8-10% CO2 due to excess air. A reading of 8.5% indicates significant excess air (approximately 35-40% excess). Higher excess air = more heat wasted heating unused air. Target: 8.5-10% CO2 for natural gas furnaces.',keyConcept:'Natural gas flue gas CO2: stoichiometric max ~12%. Typical well-adjusted furnace: 8-10%. Lower CO2 = more excess air = more heat loss. Optimize to 8.5-10% for efficiency.'},
{id:78,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'How does excess air affect combustion efficiency?',options:['A) More excess air always increases efficiency by ensuring complete combustion','B) Too much excess air reduces efficiency by heating excess nitrogen and unused oxygen, increasing flue gas volume and heat loss through the vent','C) Excess air has no effect on efficiency — only CO production matters','D) Less air always increases efficiency — CO production is acceptable'],answer:1,explanation:'Excess air is necessary to prevent CO production, but too much excess air wastes energy by heating air that does not contribute to combustion. The nitrogen in air carries heat up the flue. Optimal excess air for NG: 5-15% (80-85% CO2 of max). Below: CO production. Above: unnecessary heat loss. Combustion analysis optimizes this balance.',keyConcept:'Excess air: needed to prevent CO, but too much = heat loss (heating N2/O2). Optimal: 5-15% excess air. Measured indirectly: CO2 close to maximum = low excess air.'},
{id:79,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What does a high stack (flue gas) temperature indicate about appliance efficiency?',options:['A) High stack temperature means the appliance is working at maximum efficiency','B) High stack temperature means heat is being wasted up the flue — the appliance is not extracting maximum heat from the combustion gases, reducing efficiency','C) Stack temperature should always exceed 200°C for safety','D) Stack temperature is irrelevant to efficiency measurements'],answer:1,explanation:'The stack temperature indicates how much heat the appliance has extracted from flue gases. A low flue gas temperature means more heat was transferred to the conditioned space. High stack temp = heat being wasted up the flue. Typical residential NG furnace stack temp: 170-230°C. Condensing furnaces: 40-65°C (they extract so much heat flue gas condenses).',keyConcept:'Stack temp: indicator of heat extraction. High = heat wasted. Low = more efficient. Condensing furnaces: 40-65°C. Non-condensing: 150-230°C. Measure with combustion analyzer thermocouple.'},
{id:80,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What causes carbon monoxide (CO) production in a gas appliance?',options:['A) Excess air — too much oxygen oxidizes carbon to CO instead of CO2','B) Incomplete combustion due to insufficient air, quenching (flame hitting cold surface), incorrect gas pressure, or burner contamination — carbon atoms do not fully oxidize to CO2','C) CO is always produced in equal proportion to CO2','D) CO is only produced when propane is burned, not natural gas'],answer:1,explanation:'CO is produced when carbon atoms in fuel do not fully oxidize to CO2. Causes: insufficient combustion air, flame quenching (hitting a cold heat exchanger), oversized burner orifice (high gas flow), clogged burner ports, incorrect gas pressure, or heat exchanger recirculation. CO is odourless and toxic — combustion analysis is the only way to detect it.',keyConcept:'CO causes: insufficient air, flame quenching, high gas pressure, dirty burner, cracked heat exchanger. CO is odourless — only detectable with analyzer or CO detector. Target <100 ppm undiluted flue.'},
{id:81,topic:'combustion',topicLabel:'Combustion Theory',diff:'hard',text:'A room contains an atmospheric gas furnace and water heater with a combined input of 150,000 BTU/h. Calculate the required free area of combustion air openings for a confined space installation.',options:['A) 0.08 m²/kW × 44 kW = 3.5 m² — two openings each at 1.75 m² free area','B) 0.08 m²/kW × 44 kW = 3.52 m² total free area — typically two openings of 1.76 m² each at high and low positions','C) One opening of 0.3 m × 0.3 m is sufficient for any residential installation','D) 0.04 m²/kW for furnaces + 0.04 m²/kW for water heaters = separate calculations'],answer:1,explanation:'CSA B149.1 combustion air calculation: Convert BTU/h to kW: 150,000 ÷ 3,412 = 44 kW. Required free area = 44 kW × 0.08 m²/kW = 3.52 m². Two openings required: one within 300mm of ceiling, one within 300mm of floor — each 1.76 m² free area. Louvre area ≠ free area — louvre free area is typically 60-80% of gross area.',keyConcept:'Combustion air formula: BTU/h ÷ 3412 = kW; kW × 0.08 m²/kW = required free area. Two openings: high + low. Louvre free area = ~75% of gross. Applies to open-combustion appliances in confined spaces.'},
{id:82,topic:'combustion',topicLabel:'Combustion Theory',diff:'hard',text:'At what flue gas temperature will condensation occur in a natural gas appliance vent, and why does this matter?',options:['A) Condensation occurs at 100°C (212°F) — the boiling point of water','B) The dew point of natural gas flue gases is approximately 55-60°C (130-140°F). Below this temperature, water vapour condenses in the vent, producing acidic condensate','C) Condensation only occurs in propane appliances — natural gas flue gas does not condense','D) There is no specific dew point — condensation depends only on ambient temperature'],answer:1,explanation:'Natural gas combustion produces CO2 and H2O. At the dew point (~55-60°C for NG flue gas), water vapour condenses into liquid. The condensate absorbs CO2 forming carbonic acid (H2CO3) and sulfurous acid, producing an acidic liquid (pH 3-4). This is why ordinary metal vents corrode when serving Category IV condensing appliances.',keyConcept:'NG flue gas dew point: ~55-60°C. Below dew point = condensate forms. Acidic condensate (pH 3-4) corrodes ordinary metal vents. Category I: stay above dew point. Category IV: designed for condensing conditions.'},
{id:83,topic:'combustion',topicLabel:'Combustion Theory',diff:'hard',text:'A combustion analyzer shows O2 = 10%, CO2 = 7%, CO = 350 ppm in a gas furnace flue. What do these readings indicate and what action is required?',options:['A) Normal readings — no action needed','B) High excess air (10% O2) with significant CO (350 ppm) indicates incomplete combustion likely from burner contamination, heat exchanger restriction, or poor primary air. Investigate and correct before leaving appliance in service','C) The CO2 reading confirms complete combustion — ignore CO','D) Reduce gas pressure to lower CO output'],answer:1,explanation:'Analysis: 10% O2 = high excess air (~90% theoretical air excess). High excess air with high CO (>100 ppm) is unusual — normally excess air helps complete combustion. This combination suggests: burner contamination (blocking primary air), heat exchanger restriction causing recirculation, or abnormal combustion. 350 ppm CO exceeds recommended limit. Investigate before leaving.',keyConcept:'High O2 + high CO = abnormal — usually these are inverse. Possible cause: heat exchanger recirculation, severe burner contamination, or cracked heat exchanger allowing dilution air to mix. Always investigate.'},
{id:84,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What is a flame rollout and what are its most common causes?',options:['A) A flame that has grown too tall due to high gas pressure','B) Flames that escape the burner compartment, typically caused by blocked flue, cracked heat exchanger, or insufficient combustion air','C) A burner that repeatedly extinguishes and re-ignites','D) Burner flame that rolls into the secondary heat exchanger on a high-efficiency furnace'],answer:1,explanation:'Flame rollout occurs when combustion gases cannot properly exit through the heat exchanger — they reverse direction and exit through the burner compartment opening. Causes: blocked or restricted flue, cracked heat exchanger (allows pressure reversal), severely restricted combustion air, or inducer failure. Rollout is a serious safety hazard as it can ignite adjacent combustibles.',keyConcept:'Flame rollout: flames exit burner compartment. Causes: blocked flue, cracked heat exchanger, inadequate combustion air, failed inducer. Rollout safety switches detect this and shut down the burner.'},
{id:85,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What is a combustion analyzer used for during gas appliance commissioning?',options:['A) To measure gas flow rate through the appliance','B) To measure flue gas composition (CO2, O2, CO, flue temperature) to verify complete combustion, optimal efficiency, and safe operation','C) To detect gas leaks in the supply piping','D) To measure electrical consumption of the appliance'],answer:1,explanation:'A combustion analyzer (flue gas analyzer) measures: CO2 or O2 percentage (indicates excess air level), CO concentration (safety check), flue gas temperature (efficiency indicator), and calculates derived values like combustion efficiency, excess air %, and CO air-free. Used during commissioning and annual service to optimize and verify appliance safety.',keyConcept:'Combustion analyzer: measures CO2/O2, CO, flue temp → calculates efficiency. Use at every commissioning and annual service. Probe inserted in flue gas stream, not diluted with room air.'},
{id:86,topic:'combustion',topicLabel:'Combustion Theory',diff:'medium',text:'What is flame rectification (flame sensing) and how does it work in modern gas furnaces?',options:['A) A safety circuit where a thermocouple generates DC voltage to prove pilot flame','B) A safety technique using the ionizing property of a flame — an AC voltage applied between a sensor rod and burner ground causes DC current to flow only when flame is present, proving burner ignition','C) A method to correct the shape of an abnormal flame using air baffles','D) A sensor that detects the blue colour of a normal gas flame'],answer:1,explanation:'Flame rectification uses the ionizing property of combustion gases. An AC signal is applied between the flame rod (sensor) and the burner ground. The flame acts as a diode — it rectifies AC to DC. The control board detects the DC current (microamps) as proof of flame. If flame fails, DC stops, and the board shuts the gas valve within 1-2 seconds.',keyConcept:'Flame rectification: AC applied to flame rod → flame ionizes and rectifies to DC → board detects DC = flame proven. Fast response (<2 sec). Sensor checks: clean with fine steel wool if microamp reading too low.'},
// ── SAFETY & CODE (87-100) ──
{id:87,topic:'safety',topicLabel:'Safety & Code',diff:'easy',text:'What is the FIRST action when you suspect a gas leak in a building?',options:['A) Attempt to find the leak with a soap solution','B) Do not operate any electrical switches — leave the building immediately, shut off gas at the exterior meter shutoff, and call the gas utility from outside the building','C) Open all windows to ventilate and then search for the leak','D) Call 911 from inside the building first'],answer:1,explanation:'Gas leak response (CSA B149.1 Appendix): DO NOT operate any electrical device (switches, phones) — any spark can ignite gas. Leave the building immediately. Shut off gas at the exterior meter shutoff (if safe to do so). Call the gas utility from outside. Do not re-enter until the utility has cleared the building.',keyConcept:'Gas leak: NO switches/electrical → leave immediately → shut off at exterior meter → call utility from outside. Do not ventilate by opening windows inside — this creates ignition opportunities.'},
{id:88,topic:'safety',topicLabel:'Safety & Code',diff:'easy',text:'What does CSA B149.1 govern?',options:['A) Electrical wiring near gas appliances','B) Natural Gas and Propane Installation Code — the primary Canadian code governing gas fitting work including piping, appliances, venting, combustion air, and pressure testing','C) Gas equipment manufacturing standards','D) Occupational health and safety for gas fitters'],answer:1,explanation:'CSA B149.1 (Natural Gas and Propane Installation Code) is the primary national code for gas installation work in Canada. It covers: gas supply systems, piping materials and sizing, appliance installation, venting, combustion air, pressure testing, and safety requirements. Adopted by provinces with local amendments.',keyConcept:'CSA B149.1: the gas code. Covers piping, appliances, venting, combustion air, safety. Adopted by provinces. Gas fitters must know this code thoroughly — it governs all 403A work.'},
{id:89,topic:'safety',topicLabel:'Safety & Code',diff:'easy',text:'What are the early symptoms of carbon monoxide (CO) poisoning?',options:['A) Strong smell similar to rotten eggs and burning sensation in throat','B) Headache, dizziness, nausea, and confusion — symptoms that improve when leaving the building and worsen when returning','C) Difficulty breathing due to CO being heavier than oxygen','D) Skin discolouration and high fever immediately upon exposure'],answer:1,explanation:'CO (carbon monoxide) is odourless and colourless. Early symptoms: headache, dizziness, nausea, weakness, and confusion — often mistaken for the flu. Key distinguishing feature: symptoms improve when leaving the building (away from CO source) and worsen upon return. Severe exposure causes unconsciousness and death.',keyConcept:'CO symptoms: headache, dizziness, nausea, confusion. Improve when leaving → return = CO source in building. CO is odourless — only CO detector or combustion analyzer can detect it directly.'},
{id:90,topic:'safety',topicLabel:'Safety & Code',diff:'easy',text:'When is a permit required for gas fitting work in most Canadian jurisdictions?',options:['A) Permits are only required for new construction — not renovations','B) A permit is required for any new gas installation, extension of piping, addition of appliances, or modification of existing gas systems — minor maintenance may be exempt','C) Permits are never required for gas work done by a licensed 403A Red Seal holder','D) Permits are only required for commercial installations'],answer:1,explanation:'Most provincial regulations require permits for gas fitting work: new installations, adding appliances, extending or modifying gas piping, changing appliance type, or any work that requires inspection. Minor maintenance (replacing a burner orifice, thermocouple, or filter) typically does not require a permit. Always verify with the local Technical Standards and Safety Authority (TSSA) or equivalent.',keyConcept:'Gas permit required: new installations, appliance additions, piping extensions/modifications. Not required: minor maintenance on existing appliances. Always verify with provincial authority (TSSA in Ontario).'},
{id:91,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'What is the difference between a Class A and Class B Gas Fitter license?',options:['A) Class A is for natural gas only; Class B is for propane only','B) Class A (403A): licensed for all gas systems including high-pressure industrial installations. Class B (403B): limited to residential/light commercial appliances at standard operating pressures','C) Class A is the apprentice level; Class B is the journeyman level','D) Class B has fewer restrictions than Class A'],answer:1,explanation:'Class A Gas Fitter (403A Red Seal) is licensed for all types and pressures of gas systems — residential, commercial, and industrial including high-pressure piping and supply infrastructure. Class B Gas Fitter is restricted to residential and light commercial appliance installation and service at standard (low) operating pressures.',keyConcept:'403A (Class A): unrestricted — all pressures, residential/commercial/industrial. 403B (Class B): restricted to residential/light commercial at standard pressures. Red Seal covers Class A only.'},
{id:92,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'What is the correct procedure for purging a new gas piping system before lighting appliances?',options:['A) Open all appliance valves and let gas flow for 60 seconds to purge the system','B) Purge by allowing gas to slowly displace air from the piping system at a low-pressure vent point or appliance connection, monitoring with a combustible gas detector until gas composition is confirmed at an unconfined outdoor location','C) Purge using nitrogen, then switch to gas','D) Light the pilot repeatedly — purging happens automatically during ignition attempts'],answer:1,explanation:'Purging replaces air in new gas piping with gas. CSA B149.1 requires purging at a low point or appliance connection using a controlled vent to the exterior. Never purge into an enclosed space (explosion risk). Monitor with a combustible gas detector to confirm air is displaced. The first gas/air mixture vented may be in the flammable range — keep ignition sources away.',keyConcept:'Purging new piping: vent gas to exterior (never into enclosed space). Keep ignition sources away — first expelled mixture may be flammable. Confirm completion with gas detector. Document purge.'},
{id:93,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'What is the Lower Explosive Limit (LEL) of natural gas and what does it mean?',options:['A) 1% natural gas concentration — below this level gas will not ignite','B) 5% natural gas in air — the minimum concentration at which natural gas will ignite if an ignition source is present (Upper Explosive Limit = 15%)','C) 15% natural gas concentration — the maximum explosive level','D) 0.5% — the threshold for immediate evacuation'],answer:1,explanation:'Natural gas explosive range: LEL = 5% (minimum ignition concentration) to UEL = 15% (maximum ignition concentration). Below 5% = too lean to ignite. Above 15% = too rich to ignite (but becomes explosive as it disperses). Gas detectors typically alarm at 10-25% of LEL (~0.5-1.25% actual concentration) to provide warning well before reaching the explosive range.',keyConcept:'NG explosive range: 5-15% concentration. LEL=5%, UEL=15%. Gas detectors alarm at 10-25% of LEL (0.5-1.25%). Propane: LEL=2.1%, UEL=9.5%.'},
{id:94,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'Where should a combustible gas detector be positioned for a natural gas leak vs. a propane leak?',options:['A) Always at floor level for both natural gas and propane','B) Natural gas detector: near the ceiling (gas rises). Propane detector: near the floor (propane settles in low areas)','C) Always at breathing height (1.2 m) for both gases','D) Detector position does not matter — both gases disperse evenly'],answer:1,explanation:'Gas detector placement follows gas behaviour: Natural gas (SG=0.55, lighter than air) rises to the ceiling when leaked — detector within 300mm of ceiling. Propane (SG=1.52, heavier than air) settles to the floor — detector within 300mm of floor. Wrong placement means the detector may not alarm until dangerous concentrations exist.',keyConcept:'Gas detector placement: Natural gas = near ceiling (rises). Propane = near floor (settles). Wrong placement = delayed alarm. Fixed detectors must match the gas type for the space.'},
{id:95,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'What is a lockout/tagout (LOTO) procedure for gas systems and when is it required?',options:['A) LOTO is for electrical systems only — gas systems use manual shutoff valves','B) LOTO requires closing and locking the gas supply valve and attaching a danger tag before performing maintenance, to prevent accidental re-energization of the gas supply while work is in progress','C) Only required for high-pressure industrial gas systems','D) LOTO for gas means attaching a warning label to the appliance'],answer:1,explanation:'LOTO for gas systems: 1) Close the supply valve, 2) Lock the valve in the closed position with a lockout device, 3) Attach a danger tag with worker\'s name and warning, 4) Verify zero energy (test downstream for gas flow/pressure). This prevents another worker from inadvertently opening the gas supply during maintenance.',keyConcept:'Gas LOTO: close valve → lock → tag → verify zero gas pressure downstream. Required for maintenance on appliances and piping. Especially critical in commercial/industrial settings with multiple workers.'},
{id:96,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'What precautions are required when performing gas work in a space with electrical hazards (e.g., near a service panel)?',options:['A) Gas and electrical work can proceed simultaneously with no special precautions','B) Maintain required clearances from electrical equipment, ensure gas is shut off before working, ensure no gas atmosphere exists before electrical work (test with combustible gas detector), and coordinate with electrician if both trades must work simultaneously','C) Only a licensed electrician may be present when gas work is done near electrical panels','D) Cover all electrical panels with plastic sheeting during gas work'],answer:1,explanation:'Working near electrical equipment with gas: 1) Verify no gas atmosphere before any electrical work (combustible gas detector reading <10% LEL), 2) Maintain minimum clearances from panels and conductors, 3) Never strike an arc or create sparks near gas piping, 4) Coordinate with electrical trades. Gas-air mixtures can be ignited by arc flash.',keyConcept:'Gas near electrical: verify no gas atmosphere before any sparks. Maintain clearances. No sparks near gas piping. Coordinate trades. Use combustible gas detector to verify atmosphere.'},
{id:97,topic:'safety',topicLabel:'Safety & Code',diff:'hard',text:'A 403A gas fitter completes installation and commissioning of a new gas appliance. The appliance appears to operate correctly but combustion analysis shows CO = 450 ppm in flue gas. What is the CORRECT action?',options:['A) Document the reading and leave — 450 ppm in flue gas is acceptable','B) The appliance must not be left in service — shut it down, tag it out, investigate the cause of high CO, repair before returning to service, and notify the owner of the CO hazard','C) Simply adjust the gas pressure down by 0.5 in WC to reduce CO output','D) CO in flue gas is normal — only CO in room air matters'],answer:1,explanation:'450 ppm CO in undiluted flue gas exceeds safe levels (generally <100 ppm, investigation required >200 ppm). The appliance is producing unsafe levels of CO that will contaminate the building air. Correct action: shut down and tag out the appliance, investigate root cause (combustion air, gas pressure, burner condition, heat exchanger), repair, retest, and document. Do not leave a CO-producing appliance running.',keyConcept:'CO >200 ppm in flue gas: shut down + tag out + investigate. 403A technician liability: leaving a CO-producing appliance running can result in occupant injury and professional liability.'},
{id:98,topic:'safety',topicLabel:'Safety & Code',diff:'hard',text:'When must a 403A gas fitter notify the gas utility or Technical Standards and Safety Authority (TSSA/equivalent) about a discovered unsafe condition?',options:['A) Only if the gas fitter caused the unsafe condition during their work','B) A 403A gas fitter is legally required to report immediately discovered, existing unsafe conditions — including damaged piping, non-code-compliant installations, or appliances posing imminent danger — to the appropriate authority','C) Reporting is optional — only required if the owner requests it','D) Report only after completing the repair, not before'],answer:1,explanation:'Gas fitters are legally required to report immediately dangerous conditions to the gas utility or provincial safety authority (e.g., TSSA in Ontario). This includes: severely damaged piping, illegal installations posing immediate hazard, or appliances producing dangerous CO levels that cannot be corrected on site. The fitter must advise the owner and document the finding regardless of whether they can correct it.',keyConcept:'Mandatory reporting: gas fitter must report immediately dangerous conditions to utility/TSSA. Document finding. Advise owner. Do not leave unsafe appliance in service. Failure to report = regulatory violation.'},
{id:99,topic:'safety',topicLabel:'Safety & Code',diff:'medium',text:'What information must be recorded and provided to the building owner after commissioning a gas appliance?',options:['A) The appliance serial number only','B) Commissioning documentation should include: gas supply pressure, manifold pressure, combustion analysis readings (CO, CO2, flue temp), safety control verification results, and any deficiencies noted or corrected','C) Only the date of installation is required','D) No documentation is required for residential gas work'],answer:1,explanation:'Professional commissioning documentation provides proof of safe installation and a baseline for future service. Records should include: inlet gas pressure, manifold/burner pressure, combustion analysis (CO2, O2, CO, flue temp, efficiency), safety control test results, vent check, and any deficiencies noted and corrected. Some jurisdictions require documentation submission to the authority.',keyConcept:'Commissioning records: gas pressures + combustion analysis + safety control results. Provide copy to owner. Keep copy in service records. Good practice and often regulatory requirement.'},
{id:100,topic:'safety',topicLabel:'Safety & Code',diff:'hard',text:'A 403A gas fitter discovers an existing gas installation where the piping runs through an enclosed wall cavity with a union fitting inside the wall. The installation is 15 years old and was done with a permit. What action is required?',options:['A) No action — the installation was permitted and approved 15 years ago','B) The union fitting in the wall cavity is a code violation (CSA B149.1 prohibits mechanical joints in concealed spaces) — the owner must be advised, and the installation should be corrected. As-found condition should be documented','C) Since it was permitted, it can remain — previous permits grandfather all violations','D) Remove the union only if it is currently leaking'],answer:1,explanation:'CSA B149.1 prohibits mechanical joints (unions, couplings) in concealed spaces regardless of when installed. The standard is the current code, not the code at time of installation. A discovered violation must be brought to the owner\'s attention. The gas fitter should document the as-found condition, advise correction, and may be required to report if there is immediate hazard.',keyConcept:'Code compliance is based on current code, not historical code at time of installation. Gas fitters discovering violations: document + advise owner. Report immediately dangerous conditions to authority.'}
];
"""

JS_ENGINE = r"""
];
let filtered=[],currentIdx=0,answered={},currentTopic='all',currentDiff='all';
let mockQs=[],mockIdx=0,mockAnswers=[],mockTimer=null,mockSecondsLeft=0;
function initStreak(){const today=new Date().toDateString();const lastDate=localStorage.getItem('streakDate');const yesterday=new Date(Date.now()-86400000).toDateString();let streak=parseInt(localStorage.getItem('studyStreak')||'0');if(lastDate===today){}else if(lastDate===yesterday){streak++;localStorage.setItem('studyStreak',streak);localStorage.setItem('streakDate',today);}else{streak=1;localStorage.setItem('studyStreak',streak);localStorage.setItem('streakDate',today);}const todayKey='todayDate_'+MOCK_PAGE_KEY;const correctKey='todayCorrect_'+MOCK_PAGE_KEY;if(localStorage.getItem(todayKey)!==today){localStorage.setItem(todayKey,today);localStorage.setItem(correctKey,'0');}updateStreakDisplay();}
function updateStreakDisplay(){const streak=parseInt(localStorage.getItem('studyStreak')||'0');const correct=parseInt(localStorage.getItem('todayCorrect_'+MOCK_PAGE_KEY)||'0');const el=document.getElementById('streakDisplay');if(el)el.innerHTML=`&#x1F525; ${streak}-day streak &nbsp;|&nbsp; &#x2705; ${correct} correct today`;}
function applyFilter(){let base;if(currentTopic==='wrongbank'){const wb=JSON.parse(localStorage.getItem('wrongBank_403a')||'[]');base=questions.filter(q=>wb.includes(q.id));}else{base=questions.filter(q=>currentTopic==='all'||q.topic===currentTopic);}filtered=currentDiff==='all'?base:base.filter(q=>q.diff===currentDiff);currentIdx=0;answered={};updateScore();loadQuestion();if(typeof fcQs!=='undefined'&&document.getElementById('flashcardSection')?.style.display==='block')initFlashcards();}
function setTopic(t,btn){currentTopic=t;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');applyFilter();}
function setDiff(d,btn){currentDiff=d;document.querySelectorAll('.diff-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');applyFilter();}
function loadQuestion(){const card=document.getElementById('questionCard');if(!filtered.length){card.innerHTML='<p style="color:var(--muted);text-align:center;padding:40px;">No questions match this filter.</p>';document.getElementById('qCounter').textContent='';return;}const q=filtered[currentIdx];const isAnswered=answered[currentIdx]!==undefined;const userAns=answered[currentIdx];const letters=['A','B','C','D'];card.innerHTML=`<div class="q-header"><span class="q-topic">${q.topicLabel}</span><span class="q-diff ${q.diff}">${q.diff.charAt(0).toUpperCase()+q.diff.slice(1)}</span></div><div class="q-number">Question ${currentIdx+1} of ${filtered.length}</div><div class="q-text" id="qText">${q.text}</div><div class="options">${q.options.map((o,i)=>`<button class="option-btn${isAnswered?(i===q.answer?' reveal':(i===userAns?' wrong':'')):''}\" onclick="selectAnswer(${i})" ${isAnswered?'disabled':''}><span class="option-letter">${letters[i]}</span><span>${o.replace(/^[A-D]\)\s*/,'')}</span></button>`).join('')}</div><div class="explanation ${isAnswered?'show':''}">${isAnswered?`<strong>Explanation:</strong> ${q.explanation}<div class="key-concept"><strong>Key Concept:</strong> ${q.keyConcept}</div>`:''}</div>`;document.getElementById('prevBtn').disabled=currentIdx===0;document.getElementById('nextBtn').disabled=currentIdx===filtered.length-1;document.getElementById('qCounter').textContent=`${currentIdx+1} / ${filtered.length}`;}
function selectAnswer(i){if(answered[currentIdx]!==undefined)return;answered[currentIdx]=i;const q=filtered[currentIdx];const isCorrect=i===q.answer;if(isCorrect){const c=parseInt(localStorage.getItem('todayCorrect_'+MOCK_PAGE_KEY)||'0')+1;localStorage.setItem('todayCorrect_'+MOCK_PAGE_KEY,c);}const wb=JSON.parse(localStorage.getItem('wrongBank_403a')||'[]');if(!isCorrect){if(!wb.includes(q.id)){wb.push(q.id);localStorage.setItem('wrongBank_403a',JSON.stringify(wb));}}else{const idx=wb.indexOf(q.id);if(idx>-1){wb.splice(idx,1);localStorage.setItem('wrongBank_403a',JSON.stringify(wb));}}updateWrongBankTab();if(typeof recordTopicStat==='function')recordTopicStat(q.topic,isCorrect);if(isCorrect){window._cs=(window._cs||0)+1;if(window._cs>=2)showComboToast(window._cs);}else{window._cs=0;}updateScore();loadQuestion();updateStreakDisplay();}
function navigate(dir){currentIdx=Math.max(0,Math.min(filtered.length-1,currentIdx+dir));loadQuestion();}
function updateScore(){const realCorrect=Object.keys(answered).filter(i=>answered[i]===filtered[i]?.answer).length;const total=Object.keys(answered).length;document.getElementById('scoreDisplay').textContent=`${realCorrect} / ${total}`;document.getElementById('progressBar').style.width=filtered.length?`${((currentIdx+1)/filtered.length)*100}%`:'0%';}
function buildMockQs(n){const byTopic={};questions.forEach(q=>{if(!byTopic[q.topic])byTopic[q.topic]=[];byTopic[q.topic].push(q);});const topics=Object.keys(byTopic);const perTopic=Math.floor(n/topics.length);let pool=[];topics.forEach(t=>{const sh=[...byTopic[t]].sort(()=>Math.random()-.5);pool=pool.concat(sh.slice(0,perTopic));});while(pool.length<n){const all=[...questions].sort(()=>Math.random()-.5);for(const q of all){if(!pool.includes(q)){pool.push(q);if(pool.length>=n)break;}}}return pool.slice(0,n).sort(()=>Math.random()-.5);}
function openMockSetup(){document.getElementById('mockOverlay').style.display='flex';document.getElementById('mockBody').innerHTML=`<p style="font-size:.95rem;font-weight:600;color:#1a3a5c;margin-bottom:16px;">Select number of questions:</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><button class="mock-count-btn" onclick="startMockExam(25)"><div style="font-size:1.5rem;font-weight:800;">25</div><div style="font-size:.78rem;color:var(--muted);">~38 min</div></button><button class="mock-count-btn" onclick="startMockExam(50)"><div style="font-size:1.5rem;font-weight:800;">50</div><div style="font-size:.78rem;color:var(--muted);">~75 min</div></button><button class="mock-count-btn" onclick="startMockExam(75)"><div style="font-size:1.5rem;font-weight:800;">75</div><div style="font-size:.78rem;color:var(--muted);">~113 min</div></button><button class="mock-count-btn" onclick="startMockExam(100)"><div style="font-size:1.5rem;font-weight:800;">100</div><div style="font-size:.78rem;color:var(--muted);">~150 min &middot; Real exam</div></button></div>`;}
function startMockExam(n){mockQs=buildMockQs(n);mockIdx=0;mockAnswers=[];mockSecondsLeft=n*90;startMockTimer();renderMockQ();}
function startMockTimer(){clearInterval(mockTimer);mockTimer=setInterval(()=>{mockSecondsLeft--;const m=Math.floor(mockSecondsLeft/60),s=mockSecondsLeft%60;const el=document.getElementById('mockTimerDisplay');if(el){el.textContent=`&#x23F1; ${m}:${s.toString().padStart(2,'0')}`;el.style.color=mockSecondsLeft<300?'#e74c3c':'#f0a500';}if(mockSecondsLeft<=0){clearInterval(mockTimer);showMockResults();}},1000);}
function renderMockQ(){if(mockIdx>=mockQs.length){showMockResults();return;}const q=mockQs[mockIdx];const letters=['A','B','C','D'];document.getElementById('mockBarFill').style.width=`${(mockIdx/mockQs.length)*100}%`;document.getElementById('mockBody').innerHTML=`<div style="font-size:.78rem;color:var(--muted);margin-bottom:8px;">Question ${mockIdx+1} of ${mockQs.length} &middot; <span style="color:var(--accent);font-weight:700;">${q.topicLabel}</span></div><div class="mock-q-text">${q.text}</div><div style="display:flex;flex-direction:column;gap:8px;">${q.options.map((o,i)=>`<button class="mock-opt" id="mopt${i}" onclick="answerMockQ(${i})">${letters[i]}) ${o.replace(/^[A-D]\)\s*/,'')}</button>`).join('')}</div><div class="mock-feedback" id="mockFeedback"></div><button class="btn-mock-next" id="mockNextBtn" onclick="mockNext()">Next Question &#x2192;</button>`;}
function answerMockQ(i){const q=mockQs[mockIdx];mockAnswers.push({q,chosen:i,correct:i===q.answer});document.querySelectorAll('.mock-opt').forEach((b,idx)=>{b.disabled=true;if(idx===q.answer)b.classList.add('mock-c');else if(idx===i)b.classList.add('mock-w');});const fb=document.getElementById('mockFeedback');fb.style.display='block';fb.innerHTML=`${i===q.answer?'&#x2705; Correct!':'&#x274C; Incorrect.'} <strong>Explanation:</strong> ${q.explanation}<br><div class="key-concept"><strong>Key Concept:</strong> ${q.keyConcept}</div>`;document.getElementById('mockNextBtn').style.display='block';}
function mockNext(){mockIdx++;renderMockQ();}
function showMockResults(){clearInterval(mockTimer);const correct=mockAnswers.filter(a=>a.correct).length;const total=mockQs.length;const pct=Math.round((correct/total)*100);const pass=pct>=70;const best=parseInt(localStorage.getItem('mockBest_'+MOCK_PAGE_KEY)||'0');if(pct>best)localStorage.setItem('mockBest_'+MOCK_PAGE_KEY,pct);if(typeof saveMockHistory==='function')saveMockHistory(pct,total);const wrong=mockAnswers.filter(a=>!a.correct);document.getElementById('mockBarFill').style.width='100%';document.getElementById('mockBody').innerHTML=`<div style="text-align:center;padding:20px 0;"><div style="font-size:3rem;font-weight:800;color:${pass?'#27ae60':'#e74c3c'};">${pct}%</div><div style="font-size:1.1rem;font-weight:700;color:#1a3a5c;margin:8px 0;">${pass?'&#x2705; PASS':'&#x274C; FAIL'} &mdash; ${correct}/${total} correct</div><div style="font-size:.85rem;color:var(--muted);">Pass mark: 70%</div><div style="display:flex;gap:10px;justify-content:center;margin-top:16px;flex-wrap:wrap;"><button onclick="openMockSetup()" class="btn-mock">Try Again</button><button onclick="shareMockScore(${pct})" class="btn-mock" style="background:#1a3a5c;">Share Score</button><button onclick="downloadMockResults()" class="btn-mock" style="background:#27ae60;">Download Results</button></div></div>${wrong.length?`<div style="margin-top:20px;"><p style="font-weight:700;color:#1a3a5c;margin-bottom:12px;">Review Incorrect (${wrong.length}):</p>${wrong.map(a=>`<div style="background:#fdecea;border-radius:8px;padding:12px;margin-bottom:10px;font-size:.85rem;"><strong>${a.q.text}</strong><br>Your answer: ${['A','B','C','D'][a.chosen]}) ${a.q.options[a.chosen].replace(/^[A-D]\)\s*/,'')}<br>Correct: ${['A','B','C','D'][a.q.answer]}) ${a.q.options[a.q.answer].replace(/^[A-D]\)\s*/,'')}<br><em>${a.q.explanation}</em></div>`).join('')}</div>`:''}` ;}
function shareMockScore(pct){const text=`I scored ${pct}% on the 403A Red Seal Gas Fitter Mock Exam! Practice free at https://allforyou-bit.github.io/403a.html`;if(navigator.share){navigator.share({title:'My 403A Mock Exam Score',text});}else{navigator.clipboard.writeText(text).then(()=>alert('Score copied!'));}}
function downloadMockResults(){const correct=mockAnswers.filter(a=>a.correct).length;const pct=Math.round((correct/mockAnswers.length)*100);let txt=`403A Red Seal Mock Exam Results\n${'='.repeat(40)}\nScore: ${correct}/${mockAnswers.length} (${pct}%) \u2014 ${pct>=70?'PASS':'FAIL'}\nDate: ${new Date().toLocaleDateString()}\n\n`;mockAnswers.forEach((a,i)=>{txt+=`Q${i+1} [${a.correct?'\u2713':'\u2717'}] ${a.q.text}\n   Correct: ${['A','B','C','D'][a.q.answer]}) ${a.q.options[a.q.answer].replace(/^[A-D]\)\s*/,'')}\n${a.correct?'':('   Your answer: '+['A','B','C','D'][a.chosen]+') '+a.q.options[a.chosen].replace(/^[A-D]\)\s*/,'')+'\n')}`;});const blob=new Blob([txt],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='403A-Mock-Results.txt';a.click();URL.revokeObjectURL(url);}
function closeMock(){clearInterval(mockTimer);document.getElementById('mockOverlay').style.display='none';}
function acceptCookies(){localStorage.setItem('cookieOk','1');document.getElementById('cookieBanner').style.display='none';}
function initCookieBanner(){if(!localStorage.getItem('cookieOk'))document.getElementById('cookieBanner').style.display='flex';}
function updateWrongBankTab(){const wb=JSON.parse(localStorage.getItem('wrongBank_403a')||'[]');const btn=document.getElementById('wrongBankTabBtn');if(btn){btn.textContent='\uD83D\uDCD5 Mistakes ('+wb.length+')';}}
const TOPIC_DEFS=[{key:'appliance',label:'Appliances'},{key:'supply',label:'Gas Supply'},{key:'piping',label:'Piping'},{key:'venting',label:'Venting'},{key:'combustion',label:'Combustion Theory'},{key:'safety',label:'Safety & Code'}];
function recordTopicStat(topic,correct){const stats=JSON.parse(localStorage.getItem('topicStats_403a')||'{}');if(!stats[topic])stats[topic]={c:0,t:0};stats[topic].t++;if(correct)stats[topic].c++;localStorage.setItem('topicStats_403a',JSON.stringify(stats));renderTopicProgress();}
function renderTopicProgress(){const panel=document.getElementById('topicProgressPanel');if(!panel)return;const stats=JSON.parse(localStorage.getItem('topicStats_403a')||'{}');panel.innerHTML='<div style="font-weight:700;font-size:.85rem;margin-bottom:10px;color:#1a3a5c">&#x1F4CA; Topic Progress</div>'+TOPIC_DEFS.map(td=>{const s=stats[td.key]||{c:0,t:0};const pct=s.t?Math.round(s.c/s.t*100):0;const color=pct>=70?'#27ae60':pct>=50?'#f0a500':'#e74c3c';return '<div style="margin-bottom:8px"><div style="display:flex;justify-content:space-between;font-size:.78rem;margin-bottom:3px"><span>'+td.label+'</span><span style="color:'+color+'">'+pct+'% ('+s.c+'/'+s.t+')</span></div><div style="background:#dce3ec;border-radius:6px;height:7px;overflow:hidden"><div style="width:'+pct+'%;height:100%;background:'+color+';border-radius:6px;transition:width .4s"></div></div></div>';}).join('')+'<button onclick="resetTopicStats()" style="margin-top:6px;font-size:.72rem;background:none;border:1px solid #ccc;border-radius:4px;padding:3px 8px;cursor:pointer;color:#888">Reset Stats</button>';}
function resetTopicStats(){if(!confirm('Reset all topic progress?'))return;localStorage.removeItem('topicStats_403a');renderTopicProgress();}
function saveMockHistory(pct,total){const hist=JSON.parse(localStorage.getItem('mockHistory_403a')||'[]');hist.unshift({pct,total,date:new Date().toLocaleDateString()});if(hist.length>5)hist.length=5;localStorage.setItem('mockHistory_403a',JSON.stringify(hist));renderScoreHistory();}
function renderScoreHistory(){const el=document.getElementById('scoreHistoryList');if(!el)return;const hist=JSON.parse(localStorage.getItem('mockHistory_403a')||'[]');if(!hist.length){el.innerHTML='<span style="color:#aaa;font-size:.78rem">No mock exams yet</span>';return;}el.innerHTML=hist.map(h=>{const color=h.pct>=70?'#27ae60':h.pct>=50?'#f0a500':'#e74c3c';return '<span style="display:inline-flex;align-items:center;gap:4px;background:#f4f7fb;border-radius:20px;padding:3px 10px;font-size:.78rem;font-weight:700;color:'+color+'">'+h.pct+'%<span style="font-weight:400;color:#888;font-size:.72rem">'+h.date+'</span></span>';}).join('');}
let fcIdx=0,fcQs=[],fcFlipped=false,fcKnownIds=new Set();
function setQuizMode(mode){const qcard=document.getElementById('questionCard');const fcard=document.getElementById('flashcardSection');const quizUI=document.querySelector('.score-box');const navRow=document.querySelector('.nav-row');const modeBtns=document.querySelectorAll('.mode-btn');modeBtns.forEach(b=>b.classList.remove('active'));document.querySelector('.mode-btn[data-mode="'+mode+'"]')?.classList.add('active');if(mode==='flashcard'){if(qcard)qcard.style.display='none';if(quizUI)quizUI.style.display='none';if(navRow)navRow.style.display='none';if(fcard)fcard.style.display='block';initFlashcards();}else{if(qcard)qcard.style.display='';if(quizUI)quizUI.style.display='';if(navRow)navRow.style.display='';if(fcard)fcard.style.display='none';applyFilter();}}
function initFlashcards(){fcQs=[...filtered];fcKnownIds=new Set();fcIdx=0;fcFlipped=false;renderFlashcard();}
function getRemaining(){return fcQs.filter(q=>!fcKnownIds.has(q.id));}
function renderFlashcard(){const rem=getRemaining();const counter=document.getElementById('fcCounter');const card=document.getElementById('fcCardInner');const front=document.getElementById('fcFront');const back=document.getElementById('fcBack');if(!rem.length){if(counter)counter.textContent='All done!';if(front)front.innerHTML='<p style="font-size:1.1rem;font-weight:700;color:#27ae60">&#x1F389; You\'ve reviewed all cards!</p>';if(back)back.innerHTML='';if(card)card.style.transform='';fcFlipped=false;return;}if(fcIdx>=rem.length)fcIdx=0;const q=rem[fcIdx];if(counter)counter.textContent='Card '+(fcIdx+1)+' / '+rem.length+' remaining';if(front)front.innerHTML='<p style="font-size:.75rem;font-weight:600;color:#f0a500;margin-bottom:8px;text-transform:uppercase">'+(q.topicLabel||q.topic).toUpperCase()+'</p><p style="font-size:1rem;font-weight:600;line-height:1.5">'+q.text+'</p>';if(back){const correctOpt=q.options[q.answer];back.innerHTML='<p style="font-size:.72rem;font-weight:700;color:#27ae60;margin-bottom:6px">ANSWER</p><p style="font-size:.95rem;font-weight:700;color:#1a3a5c;margin-bottom:8px">'+correctOpt.replace(/^[A-D]\)\s*/,'')+'</p><p style="font-size:.78rem;color:#555;line-height:1.5">'+q.explanation+'</p>';}if(card)card.style.transform='';fcFlipped=false;}
function flipFlashcard(){const card=document.getElementById('fcCardInner');if(!card)return;fcFlipped=!fcFlipped;card.style.transform=fcFlipped?'rotateY(180deg)':'';}
function fcNav(dir){const rem=getRemaining();if(!rem.length)return;fcIdx=(fcIdx+dir+rem.length)%rem.length;renderFlashcard();}
function fcMarkKnow(){const rem=getRemaining();if(!rem.length)return;fcKnownIds.add(rem[fcIdx].id);if(fcIdx>=getRemaining().length)fcIdx=0;renderFlashcard();}
function fcMarkAgain(){fcNav(1);}
initStreak();applyFilter();initCookieBanner();
updateWrongBankTab();renderTopicProgress();renderScoreHistory();
(function(){var savedIdx=parseInt(localStorage.getItem('progress_403a')||'0');if(savedIdx>0){currentIdx=savedIdx;if(currentIdx>=filtered.length)currentIdx=0;if(typeof loadQuestion==='function')loadQuestion();var rt=document.createElement('div');rt.style.cssText='position:fixed;bottom:80px;left:50%;transform:translateX(-50%);background:#1a3a5c;color:white;padding:12px 22px;border-radius:24px;font-size:.88rem;font-weight:600;z-index:9998;box-shadow:0 4px 16px rgba(0,0,0,.3);cursor:pointer;white-space:nowrap';rt.innerHTML='&#x1F4CC; Resumed from Q.'+(savedIdx+1)+' &nbsp;<span style="opacity:.6;font-size:.78rem">tap to dismiss</span>';rt.onclick=function(){if(rt.parentNode)rt.parentNode.removeChild(rt);};document.body.appendChild(rt);setTimeout(function(){if(rt.parentNode)rt.parentNode.removeChild(rt);},4000);}})();
"""

HTML_BOTTOM = """
</script>
<!-- EMAIL CAPTURE -->
<div style="background:linear-gradient(135deg,#1a3a5c,#2d6a9f);border-radius:16px;padding:32px 24px;color:white;text-align:center;position:relative;overflow:hidden;max-width:900px;margin:0 auto 32px">
  <p style="font-size:.7rem;font-weight:800;color:#f0a500;letter-spacing:1.5px;text-transform:uppercase;margin-bottom:10px">FREE WEEKLY TIPS</p>
  <h3 style="font-size:1.2rem;font-weight:700;margin-bottom:8px">Get New Practice Questions Every Week</h3>
  <p style="font-size:.88rem;opacity:.88;margin-bottom:22px;max-width:420px;margin-left:auto;margin-right:auto;line-height:1.65">Join fellow Red Seal candidates. Get exam tips and new questions &mdash; free.</p>
  <form id="ecForm" onsubmit="submitEmail(event)" style="display:flex;gap:10px;max-width:420px;margin:0 auto 12px;flex-wrap:wrap;justify-content:center">
    <input type="email" name="email" placeholder="your@email.com" required autocomplete="email" style="flex:1;min-width:200px;padding:12px 16px;border-radius:8px;border:none;font-size:.9rem;color:#2c3e50;font-family:inherit">
    <button type="submit" id="ecBtn" style="background:#f0a500;color:white;border:none;border-radius:8px;padding:12px 22px;font-weight:700;font-size:.88rem;cursor:pointer;white-space:nowrap;font-family:inherit">Get Free Tips &rarr;</button>
  </form>
  <div id="ecSuccess" style="display:none;background:rgba(255,255,255,.15);border-radius:8px;padding:12px 20px;font-size:.9rem;font-weight:600;max-width:380px;margin:0 auto">&#x2705; You're in! First tips arrive within 24 hours.</div>
  <p style="font-size:.72rem;opacity:.6;margin-top:10px">No spam &middot; Unsubscribe anytime &middot; Free forever</p>
</div>
<script>
async function submitEmail(e){e.preventDefault();const btn=document.getElementById('ecBtn');const email=document.getElementById('ecForm').querySelector('input[type="email"]').value;btn.textContent='Subscribing...';btn.disabled=true;try{const r=await fetch('https://formsubmit.co/ajax/lidbil515@gmail.com',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email,_subject:'New Subscriber \u2014 Red Seal Prep 403A',_captcha:'false'})});if(r.ok){document.getElementById('ecForm').style.display='none';document.getElementById('ecSuccess').style.display='block';localStorage.setItem('rsEmailSub','1');}else{btn.textContent='Try Again';btn.disabled=false;}}catch(err){btn.textContent='Try Again';btn.disabled=false;}}
(function(){if(localStorage.getItem('rsEmailSub')){const f=document.getElementById('ecForm'),s=document.getElementById('ecSuccess');if(f&&s){f.style.display='none';s.style.display='block';}}})();
</script>
<!-- RELATED ARTICLES -->
<div style="background:#f4f7fb;padding:32px 0;margin-top:0">
<div style="max-width:860px;margin:0 auto;padding:0 20px">
  <h2 style="color:#1a3a5c;font-size:1.1rem;margin:0 0 16px;padding-bottom:10px;border-bottom:3px solid #f0a500">Related Articles</h2>
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px">
    <a href="/403a-gas-fitter-career-canada.html" style="background:white;border-radius:8px;padding:16px;text-decoration:none;color:#1a3a5c;font-size:.87rem;font-weight:600;border-left:4px solid #f0a500;display:block;box-shadow:0 1px 6px rgba(0,0,0,.07)">Gas Fitter Career Guide Canada<span style="display:block;font-size:.78rem;color:#7f8c8d;font-weight:400;margin-top:4px">Career guide &amp; apprenticeship path</span></a>
    <a href="/403a-gas-fitter-salary-canada.html" style="background:white;border-radius:8px;padding:16px;text-decoration:none;color:#1a3a5c;font-size:.87rem;font-weight:600;border-left:4px solid #f0a500;display:block;box-shadow:0 1px 6px rgba(0,0,0,.07)">403A Gas Fitter Salary Guide 2026<span style="display:block;font-size:.78rem;color:#7f8c8d;font-weight:400;margin-top:4px">Province-by-province wage data</span></a>
    <a href="/how-to-pass-red-seal-403a-exam.html" style="background:white;border-radius:8px;padding:16px;text-decoration:none;color:#1a3a5c;font-size:.87rem;font-weight:600;border-left:4px solid #f0a500;display:block;box-shadow:0 1px 6px rgba(0,0,0,.07)">How to Pass the 403A Red Seal Exam<span style="display:block;font-size:.78rem;color:#7f8c8d;font-weight:400;margin-top:4px">CSA B149.1 strategy &amp; study tips</span></a>
    <a href="/common-mistakes-403a-exam.html" style="background:white;border-radius:8px;padding:16px;text-decoration:none;color:#1a3a5c;font-size:.87rem;font-weight:600;border-left:4px solid #f0a500;display:block;box-shadow:0 1px 6px rgba(0,0,0,.07)">Common Mistakes on the 403A Exam<span style="display:block;font-size:.78rem;color:#7f8c8d;font-weight:400;margin-top:4px">Top errors and how to avoid them</span></a>
  </div>
</div>
</div>
<div style="background:#fff;border-top:2px solid #e8ecf0;padding:22px 20px;text-align:center">
  <p style="font-size:.83rem;color:#666;margin-bottom:11px">This site is free. If it helped your studies, a coffee keeps it running &#9749;</p>
  <a href='https://ko-fi.com/redsealexamprep' target='_blank' rel='noopener' style="display:inline-block;background:#FF5E5B;color:white;padding:10px 26px;border-radius:8px;font-weight:700;font-size:.88rem;text-decoration:none">&#9749; Buy Me a Coffee</a>
</div>
<footer>
  <p>&copy; 2026 Red Seal Exam Prep | <a href="/about.html">About</a> | <a href="/privacy.html">Privacy</a> | <a href="/terms.html">Terms</a> | <a href="/disclaimer.html">Disclaimer</a> | <a href="/contact.html">Contact</a></p>
  <p style="margin-top:8px;">Free study resource for Canadian Red Seal trades certification candidates.</p>
</footer>
<script>
(function(){
  var nt=document.getElementById('navToggle'),nl=document.getElementById('navLinks');
  var td=document.getElementById('tradesDrop'),tb=document.getElementById('tradesBtn');
  if(nt&&nl)nt.addEventListener('click',function(){var o=nl.classList.toggle('open');nt.textContent=o?'\\u2715':'\\u2630';});
  if(tb&&td){tb.addEventListener('click',function(e){e.stopPropagation();td.classList.toggle('open');});
  document.addEventListener('click',function(){if(td)td.classList.remove('open');});}
})();
</script>
</body>
</html>"""

# Read part 1 output
out = BASE / '403a_new.html'
existing = out.read_text(encoding='utf-8')

# Append questions 51-100 + JS engine + HTML bottom
full = existing + QUESTIONS_51_100 + JS_ENGINE + HTML_BOTTOM
out.write_text(full, encoding='utf-8')

# Now replace 403a.html
final = BASE / '403a.html'
final.write_text(full, encoding='utf-8')

# Remove intermediate file
out.unlink()

# Count questions
import re
q_count = len(re.findall(r'\bid:\d+', full))
print(f"403a.html written successfully")
print(f"Total size: {len(full):,} chars")
print(f"Question count (id: matches): {q_count}")
print("Intermediate file 403a_new.html removed")
